### ISSUE TITLE
Failed Building Wheel for Sfepy Error

### ISSUE THREAD

**Issue by apaineDTI** [sfepy/sfepy#1018]
I'm having trouble with installing sfepy for the first time using Windows 10 using python 3.11.5. Using pip install sfepy command I get this error midway through install:

Building wheels for collected packages: sfepy
  Building wheel for sfepy (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for sfepy (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [29 lines of output]
      WARNING:root:sympy (optional) is missing; some tests are going to fail!
      WARNING:root:igakit (optional) is missing; you may get run-time errors
      WARNING:root:petsc4py (optional) is missing; you may get run-time errors
      WARNING:root:mpi4py (optional) is missing; you may get run-time errors
      WARNING:root:slepc4py (optional) is missing; you may get run-time errors
      WARNING:root:pymetis (optional) is missing; you may get run-time errors
      WARNING:root:scikits.umfpack (optional) is missing; you may get run-time errors
      WARNING:root:psutil (optional) is missing; you may get run-time errors
      WARNING:root:pyvista (optional) is missing; you may get run-time errors
      WARNING:root:opt_einsum (optional) is missing; you may get run-time errors
      WARNING:root:jax (optional) is missing; you may get run-time errors
      WARNING:root:dask (optional) is missing; you may get run-time errors
      WARNING:root:primme (optional) is missing; you may get run-time errors
      Traceback (most recent call last):
        File "<frozen runpy>", line 198, in _run_module_as_main
        File "<frozen runpy>", line 88, in _run_code
        File "C:\Users\Alec Paine\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\Scripts\cmake.EXE\__main__.py", line 4, in <module>
      ModuleNotFoundError: No module named 'cmake'
      Traceback (most recent call last):
        File "C:\Users\Alec Paine\AppData\Local\Temp\pip-build-env-utrp9l4w\overlay\Lib\site-packages\skbuild\setuptools_wrap.py", line 645, in setup
          cmkr = cmaker.CMaker(cmake_executable)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Alec Paine\AppData\Local\Temp\pip-build-env-utrp9l4w\overlay\Lib\site-packages\skbuild\cmaker.py", line 148, in __init__          self.cmake_version = get_cmake_version(self.cmake_executable)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Alec Paine\AppData\Local\Temp\pip-build-env-utrp9l4w\overlay\Lib\site-packages\skbuild\cmaker.py", line 105, in get_cmake_version
          raise SKBuildError(msg) from err
     
      Problem with the CMake installation, aborting build. CMake executable is C:\Users\Alec Paine\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\Scripts\cmake.EXE
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for sfepy
Failed to build sfepy
ERROR: Could not build wheels for sfepy, which is required to install pyproject.toml-based projects

**Comment by rc** [comment]
Can you run `cmake --version`?

**Comment by apaineDTI** [comment]
Running `cmake --version`

`PS C:\Users\Alec Paine\Desktop\AP_Folder\Python Codes> cmake --version 
cmake version 3.27.1`

**Comment by rc** [comment]
This seems OK. Maybe try updating scikit-build?

**Comment by DhirajSalford** [comment]
does anyone have answer to this Installation problem?

**Comment by GeorgiaLiapi** [comment]
conda install -c conda-forge sfepy

**Comment by rc** [comment]
FYI: 2024.2 is out, and `pip install sfepy` should work correctly now.
