### ISSUE TITLE
Install in Python 3.10.12

### ISSUE THREAD

**Issue by mmatera** [sfepy/sfepy#1118]
Hi,

I am trying to install sfepy inside google colaboratory, but it seems that the package is not compatible. Until some weeks ago, it used to work by forcing pip to install the older version sfepy==2022.3a1, but today it stopped working, maybe because they upgraded the interpreter version.

Digging in the reason of the failure, I found the following text in the pip log (`pip install -v -v -v sfepy`)

```
    File "<string>", line 244, in <module>
    File "<string>", line 96, in check_versions
    File "/tmp/pip-install-viuak5ug/sfepy_3453435ad65147cc8ce4b5237eafc249/./tools/build_helpers.py", line 241, in package_check
      __import__(pkg_name)
    File "/tmp/pip-build-env-yq1bit_q/overlay/local/lib/python3.10/dist-packages/tables/__init__.py", line 44, in <module>
      from .utilsextension import get_hdf5_version as _get_hdf5_version
    File "tables/utilsextension.pyx", line 1, in init tables.utilsextension
  ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
  error: subprocess-exited-with-error
 ```
Pip also complains about the version of *pyparsing*, the version of *numpy* and other packages. Bellow is the full log:
```
Using pip 23.1.2 from /usr/local/lib/python3.10/dist-packages/pip (python 3.10)
Non-user install because site-packages writeable
Created temporary directory: /tmp/pip-build-tracker-z93817vf
Initialized build tracking at /tmp/pip-build-tracker-z93817vf
Created build tracker: /tmp/pip-build-tracker-z93817vf
Entered build tracker: /tmp/pip-build-tracker-z93817vf
Created temporary directory: /tmp/pip-install-6s776719
Created temporary directory: /tmp/pip-ephem-wheel-cache-aflibk3g
1 location(s) to search for versions of sfepy:
* https://pypi.org/simple/sfepy/
Fetching project page and analyzing links: https://pypi.org/simple/sfepy/
Getting page https://pypi.org/simple/sfepy/
Found index url https://pypi.org/simple/
Looking up "https://pypi.org/simple/sfepy/" in the cache
Request header has "max_age" as 0, cache bypassed
Starting new HTTPS connection (1): pypi.org:443
[https://pypi.org:443](https://pypi.org/) "GET /simple/sfepy/ HTTP/1.1" 304 0
Fetched page https://pypi.org/simple/sfepy/ as application/vnd.pypi.simple.v1+json
  Found link https://files.pythonhosted.org/packages/1e/19/1006dab00abebc20a2d2a956405546a0cdcf26d5efb64c2aa5011a709ee4/sfepy-2022.3.a1.tar.gz (from https://pypi.org/simple/sfepy/), version: 2022.3.a1
  Found link https://files.pythonhosted.org/packages/3c/fc/e8022fdeed181454f86ae100f8608efaab309f9f22471fd15ea04c312e25/sfepy-2022.3.tar.gz (from https://pypi.org/simple/sfepy/), version: 2022.3
  Found link https://files.pythonhosted.org/packages/6f/09/b503c83e125a26f5ec66a7982077767984819188765ae4abbfe236e77022/sfepy-2022.4.tar.gz (from https://pypi.org/simple/sfepy/), version: 2022.4
  Found link https://files.pythonhosted.org/packages/e0/ec/17a5c22e8c2087fc2eb3cfe3362a087cbd9cc225c8b12d5a16fc763e1713/sfepy-2023.1.tar.gz (from https://pypi.org/simple/sfepy/), version: 2023.1
  Found link https://files.pythonhosted.org/packages/e6/46/add627cc926d1663dad9d081fd40294f03026b32242ce90c56f014e4d39f/sfepy-2023.2.tar.gz (from https://pypi.org/simple/sfepy/), version: 2023.2
  Found link https://files.pythonhosted.org/packages/93/54/8ad585450845b6d4339a22058a4a461081cf5ae089fda555785b9692a47a/sfepy-2023.3.tar.gz (from https://pypi.org/simple/sfepy/), version: 2023.3
  Found link https://files.pythonhosted.org/packages/6a/25/77bdb8e1c209c0e75da3e078be4b848595ecfba3464a3a7f59015fdcc9a7/sfepy-2023.4.tar.gz (from https://pypi.org/simple/sfepy/), version: 2023.4
  Found link https://files.pythonhosted.org/packages/ac/6f/797b75338b890e37218e2764beff6315dd001ef45ea906269f0b8056bf46/sfepy-2024.1.tar.gz (from https://pypi.org/simple/sfepy/), version: 2024.1
Skipping link: not a file: https://pypi.org/simple/sfepy/
Given no hashes to check 7 links for project 'sfepy': discarding no candidates
Collecting sfepy
  Created temporary directory: /tmp/pip-unpack-64gyvzgv
  Looking up "https://files.pythonhosted.org/packages/ac/6f/797b75338b890e37218e2764beff6315dd001ef45ea906269f0b8056bf46/sfepy-2024.1.tar.gz" in the cache
  Current age based on date: 1275
  Ignoring unknown cache-control directive: immutable
  Freshness lifetime from max-age: 365000000
  The response is "fresh", returning cached response
  365000000 > 1275
  Using cached sfepy-2024.1.tar.gz (21.5 MB)
  Added sfepy from https://files.pythonhosted.org/packages/ac/6f/797b75338b890e37218e2764beff6315dd001ef45ea906269f0b8056bf46/sfepy-2024.1.tar.gz to build tracker '/tmp/pip-build-tracker-z93817vf'
  Created temporary directory: /tmp/pip-build-env-v58amtnu
  Running command pip subprocess to install build dependencies
  Using pip 23.1.2 from /usr/local/lib/python3.10/dist-packages/pip (python 3.10)
  Ignoring numpy: markers 'python_version <= "3.9"' don't match your environment
  Collecting scikit-build>=0.16.7
    Using cached scikit_build-0.18.0-py3-none-any.whl (85 kB)
  Collecting ninja
    Using cached ninja-1.11.1.1-py2.py3-none-manylinux1_x86_64.manylinux_2_5_x86_64.whl (307 kB)
  Collecting setuptools>=46.4
    Using cached setuptools-70.1.0-py3-none-any.whl (882 kB)
  Collecting wheel
    Using cached wheel-0.43.0-py3-none-any.whl (65 kB)
  Collecting Cython<3.0,>=0.29.30
    Using cached Cython-0.29.37-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl (1.9 MB)
  Collecting matplotlib
    Using cached matplotlib-3.9.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (8.3 MB)
  Collecting meshio
    Using cached meshio-5.3.5-py3-none-any.whl (166 kB)
  Collecting oldest-supported-numpy
    Using cached oldest_supported_numpy-2023.12.21-py3-none-any.whl (4.9 kB)
  Collecting pyparsing
    Using cached pyparsing-3.1.2-py3-none-any.whl (103 kB)
    Link requires a different Python (3.10.12 not in: '>=3.7,<3.10'): https://files.pythonhosted.org/packages/99/f1/c00d6be56e1a718a3068079e3ec8ce044d7179345280f6a3f5066068af0d/scipy-1.6.2.tar.gz (from https://pypi.org/simple/scipy/) (requires-python:>=3.7,<3.10)
    Link requires a different Python (3.10.12 not in: '>=3.7,<3.10'): https://files.pythonhosted.org/packages/fe/fd/8704c7b7b34cdac850485e638346025ca57c5a859934b9aa1be5399b33b7/scipy-1.6.3.tar.gz (from https://pypi.org/simple/scipy/) (requires-python:>=3.7,<3.10)
    Link requires a different Python (3.10.12 not in: '>=3.7,<3.10'): https://files.pythonhosted.org/packages/bb/bb/944f559d554df6c9adf037aa9fc982a9706ee0e96c0d5beac701cb158900/scipy-1.7.0.tar.gz (from https://pypi.org/simple/scipy/) (requires-python:>=3.7,<3.10)
    Link requires a different Python (3.10.12 not in: '>=3.7,<3.10'): https://files.pythonhosted.org/packages/47/33/a24aec22b7be7fdb10ec117a95e1e4099890d8bbc6646902f443fc7719d1/scipy-1.7.1.tar.gz (from https://pypi.org/simple/scipy/) (requires-python:>=3.7,<3.10)
  Collecting scipy
    Using cached scipy-1.13.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (38.6 MB)
  Collecting tables
    Using cached tables-3.9.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (7.5 MB)
  Collecting distro (from scikit-build>=0.16.7)
    Using cached distro-1.9.0-py3-none-any.whl (20 kB)
  Collecting packaging (from scikit-build>=0.16.7)
    Using cached packaging-24.1-py3-none-any.whl (53 kB)
  Collecting tomli (from scikit-build>=0.16.7)
    Using cached tomli-2.0.1-py3-none-any.whl (12 kB)
  Collecting contourpy>=1.0.1 (from matplotlib)
    Using cached contourpy-1.2.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (305 kB)
  Collecting cycler>=0.10 (from matplotlib)
    Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)
  Collecting fonttools>=4.22.0 (from matplotlib)
    Using cached fonttools-4.53.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.6 MB)
  Collecting kiwisolver>=1.3.1 (from matplotlib)
    Using cached kiwisolver-1.4.5-cp310-cp310-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (1.6 MB)
  Collecting numpy>=1.23 (from matplotlib)
    Using cached numpy-2.0.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (19.3 MB)
  Collecting pillow>=8 (from matplotlib)
    Using cached pillow-10.3.0-cp310-cp310-manylinux_2_28_x86_64.whl (4.5 MB)
  Collecting python-dateutil>=2.7 (from matplotlib)
    Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
  Collecting rich (from meshio)
    Using cached rich-13.7.1-py3-none-any.whl (240 kB)
  INFO: pip is looking at multiple versions of oldest-supported-numpy to determine which version is compatible with other requirements. This could take a while.
  Collecting oldest-supported-numpy
    Using cached oldest_supported_numpy-2023.12.12-py3-none-any.whl (4.9 kB)
    Using cached oldest_supported_numpy-2023.10.25-py3-none-any.whl (4.9 kB)
    Using cached oldest_supported_numpy-2023.8.3-py3-none-any.whl (4.8 kB)
    Using cached oldest_supported_numpy-2022.11.19-py3-none-any.whl (4.9 kB)
    Using cached oldest_supported_numpy-2022.8.16-py3-none-any.whl (3.9 kB)
    Using cached oldest_supported_numpy-2022.5.28-py3-none-any.whl (3.9 kB)
    Using cached oldest_supported_numpy-2022.5.27-py3-none-any.whl (3.9 kB)
  INFO: pip is looking at multiple versions of oldest-supported-numpy to determine which version is compatible with other requirements. This could take a while.
    Using cached oldest_supported_numpy-2022.4.18-py3-none-any.whl (3.9 kB)
    Using cached oldest_supported_numpy-2022.4.10-py3-none-any.whl (3.9 kB)
    Using cached oldest_supported_numpy-2022.4.8-py3-none-any.whl (3.9 kB)
    Using cached oldest_supported_numpy-2022.3.27-py3-none-any.whl (3.9 kB)
    Using cached oldest_supported_numpy-2022.1.30-py3-none-any.whl (3.9 kB)
  INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.
    Using cached oldest_supported_numpy-0.15-py3-none-any.whl (3.8 kB)
    Using cached oldest_supported_numpy-0.14-py3-none-any.whl (3.8 kB)
    Using cached oldest_supported_numpy-0.13-py3-none-any.whl (3.8 kB)
    Using cached oldest_supported_numpy-0.12-py3-none-any.whl (3.8 kB)
    Using cached oldest_supported_numpy-0.11-py3-none-any.whl (3.8 kB)
    Using cached oldest_supported_numpy-0.10-py3-none-any.whl (3.8 kB)
    Using cached oldest_supported_numpy-0.9-py3-none-any.whl (3.8 kB)
  Collecting numexpr>=2.6.2 (from tables)
    Using cached numexpr-2.10.1-cp310-cp310-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (405 kB)
  Collecting py-cpuinfo (from tables)
    Using cached py_cpuinfo-9.0.0-py3-none-any.whl (22 kB)
  Collecting blosc2>=2.3.0 (from tables)
    Using cached blosc2-2.7.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.4 MB)
  Collecting ndindex>=1.4 (from blosc2>=2.3.0->tables)
    Using cached ndindex-1.8-py3-none-any.whl (91 kB)
  Collecting msgpack (from blosc2>=2.3.0->tables)
    Using cached msgpack-1.0.8-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (385 kB)
  Collecting six>=1.5 (from python-dateutil>=2.7->matplotlib)
    Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
  Collecting markdown-it-py>=2.2.0 (from rich->meshio)
    Using cached markdown_it_py-3.0.0-py3-none-any.whl (87 kB)
  Collecting pygments<3.0.0,>=2.13.0 (from rich->meshio)
    Using cached pygments-2.18.0-py3-none-any.whl (1.2 MB)
  Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich->meshio)
    Using cached mdurl-0.1.2-py3-none-any.whl (10.0 kB)
  Installing collected packages: py-cpuinfo, ninja, wheel, tomli, six, setuptools, pyparsing, pygments, pillow, packaging, numpy, ndindex, msgpack, mdurl, kiwisolver, fonttools, distro, Cython, cycler, scipy, scikit-build, python-dateutil, oldest-supported-numpy, numexpr, markdown-it-py, contourpy, rich, matplotlib, blosc2, tables, meshio
    Creating /tmp/pip-build-env-v58amtnu/overlay/local/bin
    changing mode of /tmp/pip-build-env-v58amtnu/overlay/local/bin/cpuinfo to 755
    changing mode of /tmp/pip-build-env-v58amtnu/overlay/local/bin/ninja to 755
    changing mode of /tmp/pip-build-env-v58amtnu/overlay/local/bin/wheel to 755
    changing mode of /tmp/pip-build-env-v58amtnu/overlay/local/bin/pygmentize to 755
    changing mode of /tmp/pip-build-env-v58amtnu/overlay/local/bin/f2py to 755
    changing mode of /tmp/pip-build-env-v58amtnu/overlay/local/bin/numpy-config to 755
    changing mode of /tmp/pip-build-env-v58amtnu/overlay/local/bin/fonttools to 755
    changing mode of /tmp/pip-build-env-v58amtnu/overlay/local/bin/pyftmerge to 755
    changing mode of /tmp/pip-build-env-v58amtnu/overlay/local/bin/pyftsubset to 755
    changing mode of /tmp/pip-build-env-v58amtnu/overlay/local/bin/ttx to 755
    changing mode of /tmp/pip-build-env-v58amtnu/overlay/local/bin/distro to 755
    changing mode of /tmp/pip-build-env-v58amtnu/overlay/local/bin/cygdb to 755
    changing mode of /tmp/pip-build-env-v58amtnu/overlay/local/bin/cython to 755
    changing mode of /tmp/pip-build-env-v58amtnu/overlay/local/bin/cythonize to 755
    changing mode of /tmp/pip-build-env-v58amtnu/overlay/local/bin/markdown-it to 755
    changing mode of /tmp/pip-build-env-v58amtnu/overlay/local/bin/pt2to3 to 755
    changing mode of /tmp/pip-build-env-v58amtnu/overlay/local/bin/ptdump to 755
    changing mode of /tmp/pip-build-env-v58amtnu/overlay/local/bin/ptrepack to 755
    changing mode of /tmp/pip-build-env-v58amtnu/overlay/local/bin/pttree to 755
    changing mode of /tmp/pip-build-env-v58amtnu/overlay/local/bin/meshio to 755
  ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
  ipython 7.34.0 requires jedi>=0.16, which is not installed.
  astropy 5.3.4 requires numpy<2,>=1.21, but you have numpy 2.0.0 which is incompatible.
  cudf-cu12 24.4.1 requires numpy<2.0a0,>=1.23, but you have numpy 2.0.0 which is incompatible.
  cupy-cuda12x 12.2.0 requires numpy<1.27,>=1.20, but you have numpy 2.0.0 which is incompatible.
  ibis-framework 8.0.0 requires numpy<2,>=1, but you have numpy 2.0.0 which is incompatible.
  imageio 2.31.6 requires pillow<10.1.0,>=8.3.2, but you have pillow 10.3.0 which is incompatible.
  numba 0.58.1 requires numpy<1.27,>=1.22, but you have numpy 2.0.0 which is incompatible.
  rmm-cu12 24.4.0 requires numpy<2.0a0,>=1.23, but you have numpy 2.0.0 which is incompatible.
  tensorflow 2.15.0 requires numpy<2.0.0,>=1.23.5, but you have numpy 2.0.0 which is incompatible.
  Successfully installed Cython-0.29.37 blosc2-2.7.0 contourpy-1.2.1 cycler-0.12.1 distro-1.9.0 fonttools-4.53.0 kiwisolver-1.4.5 markdown-it-py-3.0.0 matplotlib-3.9.0 mdurl-0.1.2 meshio-5.3.5 msgpack-1.0.8 ndindex-1.8 ninja-1.11.1.1 numexpr-2.10.1 numpy-2.0.0 oldest-supported-numpy-0.9 packaging-24.1 pillow-10.3.0 py-cpuinfo-9.0.0 pygments-2.18.0 pyparsing-3.1.2 python-dateutil-2.9.0.post0 rich-13.7.1 scikit-build-0.18.0 scipy-1.13.1 setuptools-70.1.0 six-1.16.0 tables-3.9.2 tomli-2.0.1 wheel-0.43.0
  Installing build dependencies ... done
  Running command Getting requirements to build wheel
  Traceback (most recent call last):
    File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
      main()
    File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-v58amtnu/overlay/local/lib/python3.10/dist-packages/setuptools/build_meta.py", line 327, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=[])
    File "/tmp/pip-build-env-v58amtnu/overlay/local/lib/python3.10/dist-packages/setuptools/build_meta.py", line 297, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-v58amtnu/overlay/local/lib/python3.10/dist-packages/setuptools/build_meta.py", line 497, in run_setup
      super().run_setup(setup_script=setup_script)
    File "/tmp/pip-build-env-v58amtnu/overlay/local/lib/python3.10/dist-packages/setuptools/build_meta.py", line 313, in run_setup
      exec(code, locals())
    File "<string>", line 244, in <module>
    File "<string>", line 96, in check_versions
    File "/tmp/pip-install-6s776719/sfepy_0b6f66bd31bc4b63bdac582d2518df6b/./tools/build_helpers.py", line 241, in package_check
      __import__(pkg_name)
    File "/tmp/pip-build-env-v58amtnu/overlay/local/lib/python3.10/dist-packages/tables/__init__.py", line 44, in <module>
      from .utilsextension import get_hdf5_version as _get_hdf5_version
    File "tables/utilsextension.pyx", line 1, in init tables.utilsextension
  ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /usr/bin/python3 /usr/local/lib/python3.10/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py get_requires_for_build_wheel /tmp/tmphoqf92pw
  cwd: /tmp/pip-install-6s776719/sfepy_0b6f66bd31bc4b63bdac582d2518df6b
  Getting requirements to build wheel ... error
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
Exception information:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/cli/base_command.py", line 169, in exc_logging_wrapper
    status = run_func(*args)
  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/cli/req_command.py", line 242, in wrapper
    return func(self, options, args)
  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/commands/install.py", line 377, in run
    requirement_set = resolver.resolve(
  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/resolution/resolvelib/resolver.py", line 92, in resolve
    result = self._result = resolver.resolve(
  File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/resolvelib/resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/resolvelib/resolvers.py", line 397, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/resolvelib/resolvers.py", line 173, in _add_to_criteria
    if not criterion.candidates:
  File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/resolvelib/structs.py", line 156, in __bool__
    return bool(self._sequence)
  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 155, in __bool__
    return any(self)
  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 143, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 47, in _iter_built
    candidate = func()
  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/resolution/resolvelib/factory.py", line 206, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/resolution/resolvelib/candidates.py", line 293, in __init__
    super().__init__(
  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/resolution/resolvelib/candidates.py", line 156, in __init__
    self.dist = self._prepare()
  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/resolution/resolvelib/candidates.py", line 225, in _prepare
    dist = self._prepare_distribution()
  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/resolution/resolvelib/candidates.py", line 304, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/operations/prepare.py", line 516, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/operations/prepare.py", line 631, in _prepare_linked_requirement
    dist = _get_prepared_distribution(
  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/operations/prepare.py", line 69, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(
  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/distributions/sdist.py", line 48, in prepare_distribution_metadata
    self._install_build_reqs(finder)
  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/distributions/sdist.py", line 118, in _install_build_reqs
    build_reqs = self._get_build_requires_wheel()
  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/distributions/sdist.py", line 95, in _get_build_requires_wheel
    return backend.get_requires_for_build_wheel()
  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/utils/misc.py", line 692, in get_requires_for_build_wheel
    return super().get_requires_for_build_wheel(config_settings=cs)
  File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyproject_hooks/_impl.py", line 166, in get_requires_for_build_wheel
    return self._call_hook('get_requires_for_build_wheel', {
  File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyproject_hooks/_impl.py", line 311, in _call_hook
    self._subprocess_runner(
  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/utils/subprocess.py", line 252, in runner
    call_subprocess(
  File "/usr/local/lib/python3.10/dist-packages/pip/_internal/utils/subprocess.py", line 224, in call_subprocess
    raise error
pip._internal.exceptions.InstallationSubprocessError: Getting requirements to build wheel exited with 1
Removed sfepy from https://files.pythonhosted.org/packages/ac/6f/797b75338b890e37218e2764beff6315dd001ef45ea906269f0b8056bf46/sfepy-2024.1.tar.gz from build tracker '/tmp/pip-build-tracker-z93817vf'
Removed build tracker: '/tmp/pip-build-tracker-z93817vf'

WARNING: The following packages were previously imported in this runtime:
  [cycler,kiwisolver,six]
You must restart the runtime in order to use newly installed versions.
```

**Comment by rc** [comment]
Try forcing numpy < 2.0.0, and then install sfepy. I forgot to pin numpy version... It will be fixed in the next release.

**Comment by mmatera** [comment]
@rc I tried that, but it still does not work.

**Comment by rc** [comment]
Maybe start in a clean environment? There can be some left-overs, as pip does not handle dependencies too well.

**Comment by mmatera** [comment]
My goal was to install it in a Google Colab environment, to write some tutorials. In my laptop it works OK by just using Python 3.9, but I cannot do that in Colab.

**Comment by rc** [comment]
A new PyPI release is needed, it seems that numpy 2.0.0 is always installed over the 1.2.x. 

As a workaround, I managed to install sfepy and run tests in a colab notebook with:
```
! pip install -v -v -v --no-build-isolation scikit-build scipy cython tables meshio sympy ninja "cython<3"

! pip install -v -v -v --no-build-isolation sfepy

! sfepy-test
```
The requirements in the first command are the minimal ones, you may want to add more optional dependencies.

**Comment by mmatera** [comment]
@rc it works! Thank you very much
M

**Comment by rc** [comment]
Hth, let's close this.
