### ISSUE TITLE
Problems Installing sfepy on Mac

### ISSUE THREAD

**Issue by githumjto** [sfepy/sfepy#279]
Here are the list of errors when attempting to install sfepy on Mac.  I welcome suggestions that might resolve the problems.  Thanks.

Jons-MacBook-Pro-2:sfepy Jon$ python setup.py build_ext --inplace
non-existing path in 'sfepy/discrete/fem/extmods': '/Users/Jon/Library/Enthought/Canopy_64bit/User/include/python2.7'
non-existing path in 'sfepy/terms/extmods': '/Users/Jon/Library/Enthought/Canopy_64bit/User/include/python2.7'
running build_ext
running build_src
build_src
building library "sfepy_common" sources
building library "sfepy_terms" sources
building extension "sfepy.discrete.fem.extmods._fmfield" sources
building extension "sfepy.discrete.fem.extmods.mappings" sources
building extension "sfepy.discrete.fem.extmods.assemble" sources
building extension "sfepy.discrete.fem.extmods.bases" sources
building extension "sfepy.discrete.fem.extmods.cmesh" sources
building extension "sfepy.discrete.fem.extmods.lobatto_bases" sources
building extension "sfepy.discrete.fem.extmods._geommech" sources
building extension "sfepy.discrete.iga.extmods.igac" sources
building extension "sfepy.linalg.extmods.crcm" sources
building extension "sfepy.terms.extmods.terms" sources
building data_files sources
build_src: building npy-pkg config files
customize UnixCCompiler
Traceback (most recent call last):
  File "setup.py", line 183, in <module>
    setup_package()
  File "setup.py", line 175, in setup_package
    configuration = configuration)
  File "/Users/Jon/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/numpy/distutils/core.py", line 169, in setup
    return old_setup(**new_attr)
  File "/Applications/Canopy.app/appdata/canopy-1.5.1.2730.macosx-x86_64/Canopy.app/Contents/lib/python2.7/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/Applications/Canopy.app/appdata/canopy-1.5.1.2730.macosx-x86_64/Canopy.app/Contents/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/Applications/Canopy.app/appdata/canopy-1.5.1.2730.macosx-x86_64/Canopy.app/Contents/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/Users/Jon/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/numpy/distutils/command/build_ext.py", line 71, in run
    build_clib.run()
  File "/Users/Jon/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/numpy/distutils/command/build_clib.py", line 74, in run
    need_cxx=self.have_cxx_sources())
  File "/Users/Jon/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/numpy/distutils/ccompiler.py", line 344, in CCompiler_customize
    customize_compiler(self)
  File "/Applications/Canopy.app/appdata/canopy-1.5.1.2730.macosx-x86_64/Canopy.app/Contents/lib/python2.7/distutils/sysconfig.py", line 181, in customize_compiler
    _osx_support.customize_compiler(_config_vars)
  File "/Applications/Canopy.app/appdata/canopy-1.5.1.2730.macosx-x86_64/Canopy.app/Contents/lib/python2.7/_osx_support.py", line 418, in customize_compiler
    _find_appropriate_compiler(_config_vars)
  File "/Applications/Canopy.app/appdata/canopy-1.5.1.2730.macosx-x86_64/Canopy.app/Contents/lib/python2.7/_osx_support.py", line 185, in _find_appropriate_compiler
    if 'llvm-gcc' in data:
TypeError: argument of type 'NoneType' is not iterable

**Comment by rc** [comment]
Any news here?
