### ISSUE TITLE
149 AttributeError

### ISSUE THREAD

**Issue by lbertolotti** [sfepy/sfepy#381]
SfePy Documentation, section 3.3.2
```
lucas@lucas-K55VD:~/sfepy$ mayavi2 -V
Mayavi 4.5.0
lucas@lucas-K55VD:~/sfepy$ ./postproc.py cylinder.vtk
sfepy: point scalars t at [-0.05 -0.02  0.  ]
sfepy: range: -2.00e+00 2.00e+00 l2 norm range: 1.06e-02 2.00e+00
No handlers could be found for logger "mayavi.core.common"
Exception occurred in traits notification handler.
Please check the log file for details.
Exception occurred in traits notification handler for object: <mayavi.tools.mlab_scene_model.MlabSceneModel object at 0x7fa58bbf0d70>, trait: activated, old value: <undefined>, new value: True
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/traits/trait_notifiers.py", line 519, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "/usr/local/lib/python2.7/dist-packages/traits/trait_notifiers.py", line 482, in dispatch
    handler( *args )
  File "/home/lucas/sfepy/sfepy/postprocess/viewer.py", line 1219, in _post_init
    viewer.render_scene(self.scene, viewer.options)
  File "/home/lucas/sfepy/sfepy/postprocess/viewer.py", line 689, in render_scene
    self.build_mlab_pipeline(**options)
  File "/home/lucas/sfepy/sfepy/postprocess/viewer.py", line 529, in build_mlab_pipeline
    active = mlab.pipeline.set_active_attribute(source)
  File "/usr/local/lib/python2.7/dist-packages/mayavi/tools/pipe_base.py", line 38, in the_function
    factory = factory_class(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mayavi/tools/pipe_base.py", line 163, in __init__
    self.set(**traits)
  File "/usr/local/lib/python2.7/dist-packages/mayavi/tools/pipe_base.py", line 180, in set
    self._anytrait_changed(trait, value)
  File "/usr/local/lib/python2.7/dist-packages/mayavi/tools/pipe_base.py", line 198, in _anytrait_changed
    setattr(obj, components[-1], value)
  File "/usr/local/lib/python2.7/dist-packages/mayavi/core/trait_defs.py", line 97, in set_value
    raise TraitError(object, name,"one of %s"%values, value)
TraitError: The 'point_vectors_name' trait of a SetActiveAttribute instance must be one of [], but a value of '' <type 'str'> was specified.

```
Do I have to change my mayavi version?

**Comment by rc** [comment]
See #292 - what is your sfepy version? The bleeding edge code in the git repo should work with mayavi 4.4 and lower, I did not try it with 4.5, but it might work as well.

**Comment by rc** [comment]
@lbertolotti, any more info?

**Comment by lbertolotti** [comment]
lucas@lucas-K55VD:~/sfepy$ mayavi2 -V
Mayavi 4.3.1
lucas@lucas-K55VD:~/sfepy$ ./postproc.py cylinder.vtk
sfepy: point scalars t at [-0.05 -0.02  0.  ]
sfepy: range: -2.00e+00 2.00e+00 l2 norm range: 1.06e-02 2.00e+00

**Comment by rc** [comment]
So that worked?

**Comment by lbertolotti** [comment]
:)
![fem](https://cloud.githubusercontent.com/assets/19675068/25317434/ecd60578-284e-11e7-9fb0-310efeb0a123.png)

**Comment by rc** [comment]
OK :) There are still some issues with mayavi >= 4.4 (e.g. #394),  but that particular error you had is IMHO fixed - shall we close this?

**Comment by lbertolotti** [comment]
```
lucas@lucas-K55VD:~$ lsb_release -a
LSB Version:	core-9.20160110ubuntu0.2-amd64:core-9.20160110ubuntu0.2-noarch:security-9.20160110ubuntu0.2-amd64:security-9.20160110ubuntu0.2-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial
```
