### ISSUE TITLE
numpy 1.13.0 compatability problem

### ISSUE THREAD

**Issue by rc** [sfepy/sfepy#404]
Python 3.6

```
cython is available in version 0.25.2
numpy is available in version 1.13.0
scipy is available in version 0.19.0
matplotlib is available in version 2.0.2
pyparsing is available in version 2.1.4
tables is available in version 3.3.0
mayavi (optional) is missing; you may get run-time errors
sympy (optional) is available in version 1.0
igakit (optional) is available in version 0.1
petsc4py (optional) is missing; you may get run-time errors
mpi4py (optional) is missing; you may get run-time errors
pymetis (optional) is missing; you may get run-time errors
scikits.umfpack (optional) is available in version 0.1
pysparse (optional) is missing; you may get run-time errors
```

```
<<< [10] tests/test_high_level.py
[10] sfepy: left over: ['__name__', '__doc__', '__package__', '__loader__', '__spec__', '__file__', '__cached__', '__builtins__', 'absolute_import', 'time', 'op', 'nm', 'TestCommon', 'fix_u_fun', 'verbose', '_filename']
[10] sfepy: reading mesh [line2, tri3, quad4, tetra4, hexa8] (/home/travis/build/rc/sfepy/meshes/2d/rectangle_tri.mesh)...
[10] sfepy: ...done in 0.01 s
>>> test instance prepared (4 test(s))
[10/1] sfepy: updating variables...
[10/1] sfepy: ...done
>>> <class 'ValueError'>
Traceback (most recent call last):
  File "run_tests.py", line 234, in <module>
    sys.exit(main())
  File "run_tests.py", line 226, in main
    run_tests(stats, dirpath, filenames)
  File "run_tests.py", line 144, in run_tests
    stats[0] + 1)
  File "run_tests.py", line 108, in run_test
    ifile=ifile)
  File "/home/travis/build/rc/sfepy/sfepy/base/testing.py", line 67, in run
    ret = test_method()
  File "/home/travis/build/rc/sfepy/tests/test_high_level.py", line 157, in test_solving
    pb.time_update(ebcs=Conditions([fix_u, shift_u]))
  File "/home/travis/build/rc/sfepy/sfepy/discrete/problem.py", line 682, in time_update
    functions, create_matrix, is_matrix)
  File "/home/travis/build/rc/sfepy/sfepy/discrete/problem.py", line 640, in update_equations
    active_only=ac)
  File "/home/travis/build/rc/sfepy/sfepy/discrete/equations.py", line 305, in time_update
    active_only=active_only)
  File "/home/travis/build/rc/sfepy/sfepy/discrete/variables.py", line 413, in equation_mapping
    problem=problem)
  File "/home/travis/build/rc/sfepy/sfepy/discrete/variables.py", line 1475, in equation_mapping
    problem=problem, warn=warn)
  File "/home/travis/build/rc/sfepy/sfepy/discrete/common/dof_info.py", line 377, in map_equations
    if vv is not None: val_ebc[eq] = vv
ValueError: shape mismatch: value array of shape (41,2) could not be broadcast to indexing result of shape (82,)
```

**Comment by rc** [comment]
The same with Python 2.7. `val_ebc[eq] = vv.ravel()` fixes this problem.

**Comment by rc** [comment]
Better fix::

```
git grep 'def set_dofs'
```
and in all `set_dofs()` functions, use `numpy.ravel()` in the `if callable(fun):` branch.
