### ISSUE TITLE
Documentation and SfePy modules

### ISSUE THREAD

**Issue by lbertolotti** [sfepy/sfepy#405]
```
import numpy as nm
from sfepy.linalg.extmods.crcm import permute_in_place, rcm
from sfepy.discrete.fem import Mesh, FEDomain, Field
from sfepy.discrete import FieldVariable, Material, Integral, Equation, Equations, Function, Functions

def get_circle_1(coors, domain=None):
    r = nm.sqrt(coors[:,0]**2.0 + coors[:,1]**2.0)
    return nm.where((r<51)&(r>49))[0]
    
def get_circle_2(coors, domain=None):
    r = nm.sqrt(coors[:,0]**2.0 + coors[:,1]**2.0)
    return nm.where((r<101)&(r>99))[0]

get_circle_fun_1=Function('get_circle_fun_1', get_circle_1)
get_circle_fun_2=Function('get_circle_fun_2', get_circle_2)
from sfepy.terms.terms_diffusion import LaplaceTerm
from sfepy.terms.extmods.terms import dw_laplace
```
Here we will discuss the proper documentation for SfePy types. The relevant python objects will be marked in **black**. We will use a ring mesh in this example:
```
In: print mesh
Out: Mesh:-0000000000000000001-0000000000000000001
  cmesh:
    CMesh: n_coor: 1445, dim 3, tdim: 3, n_el 4540
  descs:
    list: ['3_4']
  dim:
    3
  dims:
    list: [3]
  io:
    None
  n_el:
    4540
  n_nod:
    1445
  name:
    -0000000000000000001-0000000000000000001
  nodal_bcs:
    dict with keys: []
domain=FEDomain('domain', mesh)
In: type(domain)
Out: sfepy.discrete.fem.domain.FEDomain
```
sfepy.discrete.fem.domain.FEDomain = class FEDomain(sfepy.discrete.common.domain.Domain)
Domain is divided into groups, whose purpose is to have homogeneous data shapes.
Methods inherited from sfepy.discrete.common.domain.Domain:
**create_region**(self, name, select, kind='cell', parent=None, check_parents=True, functions=None, add_to_regions=True, allow_empty=False)
Region factory constructor. Append the new region to self.regions list.
```
omega=domain.create_region('Omega','all')
gamma_1 = domain.create_region('Gamma_1', 'vertices by get_circle_fun_1', functions=Functions([get_circle_fun_1]), kind='vertex')
gamma_2 = domain.create_region('Gamma_2', 'vertices by get_circle_fun_2', functions=Functions([get_circle_fun_2]), kind='vertex')
field = Field.from_args('fu', nm.float64, 'vector', omega, space='H1', poly_space_base='lagrange', approx_order=2)
u=FieldVariable('u', 'unknown', field)
v=FieldVariable('v', 'test', field, primary_var_name='u')
c=Material('c', c=1.0)

from sfepy.terms import Term

integral=Integral('i', order=2)
t=Term.new('dw_laplace(c.c,v,u)', integral, omega, v=v, u=u, c=c)
In:type(t)
Out: sfepy.terms.terms_diffusion.LaplaceTerm
```
sfepy.terms.terms_diffusion.LaplaceTerm = class LaplaceTerm(DiffusionTerm)
Laplace term with :math:`c` coefficient. Can be evaluated. Can use derivatives.
:Definition:
.. math::
    \int_{\Omega} c \nabla q \cdot \nabla p \mbox{ , } \int_{\Omega}
    c \nabla \bar{p} \cdot \nabla r
 
:Arguments 1:
    - material : :math:`c`
    - virtual  : :math:`q`
    - state    : :math:`p`
 
:Arguments 2:
    - material    : :math:`c`
    - parameter_1 : :math:`\bar{p}`
    - parameter_2 : :math:`r`
Static methods inherited from sfepy.terms.terms.Term:
**new**(name, integral, region, **kwargs)
```
eq=Equation('balance', t)
eqs=Equations([eq])

from sfepy.discrete import Function
from sfepy.discrete.conditions import Conditions, EssentialBC

ebc_1=EssentialBC('ebc1', gamma_1, {'u.all' : 10.0})
ebc_2=EssentialBC('ebc2', gamma_2, {'u.all' : 10.0})

from sfepy.solvers.ls import ScipyDirect
from sfepy.solvers.nls import Newton
from sfepy.base.base import IndexedStruct
from sfepy.discrete import Problem

ls=ScipyDirect({})
nls_status=IndexedStruct()
nls=Newton({},lin_solver=ls, status=nls_status)
pb=Problem('Laplace', equations=eqs)
In: type(pb)
Out: sfepy.discrete.problem.Problem
```
sfepy.discrete.problem.Problem = class Problem(sfepy.base.base.Struct)
Methods defined here:
**time_update**(self, ts=None, ebcs=None, epbcs=None, lcbcs=None, functions=None, create_matrix=False, is_matrix=True)
**solve**(self, state0=None, nls_status=None, ls_conf=None, nls_conf=None, force_values=None, var_data=None, update_materials=True)
Solve self.equations in current time step.
Parameters

var_data : dict
    A dictionary of {variable_name : data vector} used to initialize
    parameter variables.

```
pb.time_update(ebcs=Conditions([ebc_1,ebc_2]))
pb.solve()
sfepy: updating materials...
sfepy:     c
sfepy: ...done in 0.00 s
sfepy: allowed argument shapes for term "dw_laplace.2.Omega(c.c,v,u)":
sfepy: [{'opt_material': '1, 1', 'state': 1, 'parameter_1': 1, 'virtual': (1, 'state'), 'parameter_2': 1}, {'opt_material': None, 'state': 1, 'parameter_2': 1, 'parameter_1': 1, 'virtual': (1, 'state')}]
sfepy: giving up!
Traceback (most recent call last):

  File "<ipython-input-8-8a1c43eeea40>", line 1, in <module>
    pb.solve()

  File "/usr/local/lib/python2.7/dist-packages/sfepy-2017.1_git_43ddf5fe35e29bbd65f7846f4a43692f8a535f32-py2.7-linux-x86_64.egg/sfepy/discrete/problem.py", line 1091, in solve
    vec = nls(vec0, status=self.nls_status)

  File "/usr/local/lib/python2.7/dist-packages/sfepy-2017.1_git_43ddf5fe35e29bbd65f7846f4a43692f8a535f32-py2.7-linux-x86_64.egg/sfepy/solvers/nls.py", line 254, in __call__
    vec_r = fun(vec_x)

  File "/usr/local/lib/python2.7/dist-packages/sfepy-2017.1_git_43ddf5fe35e29bbd65f7846f4a43692f8a535f32-py2.7-linux-x86_64.egg/sfepy/discrete/evaluate.py", line 54, in eval_residual
    vec_r = self.problem.equations.eval_residuals(vec)

  File "/usr/local/lib/python2.7/dist-packages/sfepy-2017.1_git_43ddf5fe35e29bbd65f7846f4a43692f8a535f32-py2.7-linux-x86_64.egg/sfepy/discrete/equations.py", line 699, in eval_residuals
    self.evaluate(mode='weak', dw_mode='vector', asm_obj=out)

  File "/usr/local/lib/python2.7/dist-packages/sfepy-2017.1_git_43ddf5fe35e29bbd65f7846f4a43692f8a535f32-py2.7-linux-x86_64.egg/sfepy/discrete/equations.py", line 635, in evaluate
    term_mode=term_mode, asm_obj=asm_obj)

  File "/usr/local/lib/python2.7/dist-packages/sfepy-2017.1_git_43ddf5fe35e29bbd65f7846f4a43692f8a535f32-py2.7-linux-x86_64.egg/sfepy/discrete/equations.py", line 852, in evaluate
    ret_status=True)

  File "/usr/local/lib/python2.7/dist-packages/sfepy-2017.1_git_43ddf5fe35e29bbd65f7846f4a43692f8a535f32-py2.7-linux-x86_64.egg/sfepy/terms/terms.py", line 1356, in evaluate
    self.check_shapes(*args)

  File "/usr/local/lib/python2.7/dist-packages/sfepy-2017.1_git_43ddf5fe35e29bbd65f7846f4a43692f8a535f32-py2.7-linux-x86_64.egg/sfepy/terms/terms.py", line 1206, in check_shapes
    % term_str)

ValueError: wrong arguments shapes for "dw_laplace.2.Omega(c.c,v,u)" term! (see above)
```

**Comment by lbertolotti** [comment]
Sfepy VERSION=2017.2-git-ff8b2712f5cbd2ce78cd2df1853884af8d543df1
```
pb.solve()
sfepy: updating materials...
sfepy:     c
sfepy: ...done in 0.02 s
sfepy: allowed argument shapes for term "+1.00e+00 * dw_laplace.2.Omega(c.c,v,u)":
sfepy: [{'opt_material': '1, 1', 'state': 1, 'parameter_1': 1, 'virtual': (1, 'state'), 'parameter_2': 1}, {'opt_material': None, 'state': 1, 'parameter_2': 1, 'parameter_1': 1, 'virtual': (1, 'state')}]
sfepy: giving up!
Traceback (most recent call last):

  File "<ipython-input-2-8a1c43eeea40>", line 1, in <module>
    pb.solve()

  File "/usr/local/lib/python2.7/dist-packages/sfepy-2017.2_git_ff8b2712f5cbd2ce78cd2df1853884af8d543df1-py2.7-linux-x86_64.egg/sfepy/discrete/problem.py", line 1093, in solve
    vec = nls(vec0, status=self.nls_status)

  File "/usr/local/lib/python2.7/dist-packages/sfepy-2017.2_git_ff8b2712f5cbd2ce78cd2df1853884af8d543df1-py2.7-linux-x86_64.egg/sfepy/solvers/nls.py", line 254, in __call__
    vec_r = fun(vec_x)

  File "/usr/local/lib/python2.7/dist-packages/sfepy-2017.2_git_ff8b2712f5cbd2ce78cd2df1853884af8d543df1-py2.7-linux-x86_64.egg/sfepy/discrete/evaluate.py", line 54, in eval_residual
    vec_r = self.problem.equations.eval_residuals(vec)

  File "/usr/local/lib/python2.7/dist-packages/sfepy-2017.2_git_ff8b2712f5cbd2ce78cd2df1853884af8d543df1-py2.7-linux-x86_64.egg/sfepy/discrete/equations.py", line 697, in eval_residuals
    self.evaluate(mode='weak', dw_mode='vector', asm_obj=out)

  File "/usr/local/lib/python2.7/dist-packages/sfepy-2017.2_git_ff8b2712f5cbd2ce78cd2df1853884af8d543df1-py2.7-linux-x86_64.egg/sfepy/discrete/equations.py", line 633, in evaluate
    term_mode=term_mode, asm_obj=asm_obj)

  File "/usr/local/lib/python2.7/dist-packages/sfepy-2017.2_git_ff8b2712f5cbd2ce78cd2df1853884af8d543df1-py2.7-linux-x86_64.egg/sfepy/discrete/equations.py", line 850, in evaluate
    ret_status=True)

  File "/usr/local/lib/python2.7/dist-packages/sfepy-2017.2_git_ff8b2712f5cbd2ce78cd2df1853884af8d543df1-py2.7-linux-x86_64.egg/sfepy/terms/terms.py", line 1364, in evaluate
    self.check_shapes(*args)

  File "/usr/local/lib/python2.7/dist-packages/sfepy-2017.2_git_ff8b2712f5cbd2ce78cd2df1853884af8d543df1-py2.7-linux-x86_64.egg/sfepy/terms/terms.py", line 1210, in check_shapes
    % term_str)

ValueError: wrong arguments shapes for "+1.00e+00 * dw_laplace.2.Omega(c.c,v,u)" term! (see above)
```
Not sure if +1.00e+00 * elucidates anything.

**Comment by lbertolotti** [comment]
2017.3+git.6b62583df3c6c70cfd6536585c4dfa19325ab563
```
pb.solve()
sfepy: updating materials...
sfepy:     c
sfepy: ...done in 0.00 s
sfepy: allowed argument shapes for term "+1.00e+00 * dw_laplace.2.Omega(c.c,v,u)":
sfepy: [{'opt_material': '1, 1', 'state': 1, 'parameter_1': 1, 'virtual': (1, 'state'), 'parameter_2': 1}, {'opt_material': None, 'state': 1, 'parameter_2': 1, 'parameter_1': 1, 'virtual': (1, 'state')}]
sfepy: actual argument shapes:
sfepy: {'virtual:v': (3,), "opt_material:('c', 'c')": (1, 1), 'state:u': (3,)}
sfepy: giving up!
Traceback (most recent call last):

  File "<ipython-input-5-49223d18e267>", line 1, in <module>
    pb.solve()

  File "/usr/local/lib/python2.7/dist-packages/sfepy-2017.3+git.6b62583df3c6c70cfd6536585c4dfa19325ab563-py2.7-linux-x86_64.egg/sfepy/discrete/problem.py", line 1093, in solve
    vec = nls(vec0, status=self.nls_status)

  File "/usr/local/lib/python2.7/dist-packages/sfepy-2017.3+git.6b62583df3c6c70cfd6536585c4dfa19325ab563-py2.7-linux-x86_64.egg/sfepy/solvers/nls.py", line 256, in __call__
    vec_r = fun(vec_x)

  File "/usr/local/lib/python2.7/dist-packages/sfepy-2017.3+git.6b62583df3c6c70cfd6536585c4dfa19325ab563-py2.7-linux-x86_64.egg/sfepy/discrete/evaluate.py", line 54, in eval_residual
    vec_r = self.problem.equations.eval_residuals(vec)

  File "/usr/local/lib/python2.7/dist-packages/sfepy-2017.3+git.6b62583df3c6c70cfd6536585c4dfa19325ab563-py2.7-linux-x86_64.egg/sfepy/discrete/equations.py", line 697, in eval_residuals
    self.evaluate(mode='weak', dw_mode='vector', asm_obj=out)

  File "/usr/local/lib/python2.7/dist-packages/sfepy-2017.3+git.6b62583df3c6c70cfd6536585c4dfa19325ab563-py2.7-linux-x86_64.egg/sfepy/discrete/equations.py", line 633, in evaluate
    term_mode=term_mode, asm_obj=asm_obj)

  File "/usr/local/lib/python2.7/dist-packages/sfepy-2017.3+git.6b62583df3c6c70cfd6536585c4dfa19325ab563-py2.7-linux-x86_64.egg/sfepy/discrete/equations.py", line 850, in evaluate
    ret_status=True)

  File "/usr/local/lib/python2.7/dist-packages/sfepy-2017.3+git.6b62583df3c6c70cfd6536585c4dfa19325ab563-py2.7-linux-x86_64.egg/sfepy/terms/terms.py", line 1371, in evaluate
    self.check_shapes(*args)

  File "/usr/local/lib/python2.7/dist-packages/sfepy-2017.3+git.6b62583df3c6c70cfd6536585c4dfa19325ab563-py2.7-linux-x86_64.egg/sfepy/terms/terms.py", line 1217, in check_shapes
    % term_str)

ValueError: wrong arguments shapes for "+1.00e+00 * dw_laplace.2.Omega(c.c,v,u)" term! (see above)
```

**Comment by lbertolotti** [comment]
The source of the problem is in the sfepy.terms.terms_diffusion.LaplaceTerm module:
```
t.evaluate()
sfepy: setting up dof connectivities...
sfepy: ...done in 0.00 s
sfepy: allowed argument shapes for term "+1.00e+00 * dw_laplace.2.Omega(c.c,v,u)":
sfepy: [{'opt_material': '1, 1', 'state': 1, 'parameter_1': 1, 'virtual': (1, 'state'), 'parameter_2': 1}, {'opt_material': None, 'state': 1, 'parameter_2': 1, 'parameter_1': 1, 'virtual': (1, 'state')}]
sfepy: actual argument shapes:
sfepy: {'virtual:v': (3,), "opt_material:('c', 'c')": (1, 1), 'state:u': (3,)}
Traceback (most recent call last):

  File "<ipython-input-70-ef2c87f74137>", line 1, in <module>
    t.evaluate()

  File "/usr/local/lib/python2.7/dist-packages/sfepy-2017.3+git.6b62583df3c6c70cfd6536585c4dfa19325ab563-py2.7-linux-x86_64.egg/sfepy/terms/terms.py", line 1339, in evaluate
    self.check_shapes(*args)

  File "/usr/local/lib/python2.7/dist-packages/sfepy-2017.3+git.6b62583df3c6c70cfd6536585c4dfa19325ab563-py2.7-linux-x86_64.egg/sfepy/terms/terms.py", line 1217, in check_shapes
    % term_str)

ValueError: wrong arguments shapes for "+1.00e+00 * dw_laplace.2.Omega(c.c,v,u)" term! (see above)

```

**Comment by rc** [comment]
Yes, and above the exception, you can compare the actual vs. required arguments shapes. Your variables have the shape 3 (vectors), while the term expects the shape 1 (scalar variables).

For div(grad(u)) where u is a vector, you dw_div_grad, please. (Yes dw_laplace and dw_div_grad could probably be merged.)

**Comment by lbertolotti** [comment]
`t=Term.new('dw_div_grad(c.c,v,u)', integral, omega, c=c, u=u, v=v)`
gives me a vector field solution:
![ring_vec](https://user-images.githubusercontent.com/19675068/31561633-e4e9a802-b02e-11e7-85e8-af1abefb760b.png)

yet, solving laplace's problem should give me a scalar solution. So instead of changing t=Term.new() I changed
`field = Field.from_args('fu', nm.float64, 1, omega, approx_order=2)`
Now giving me a scalar solution:
![ring_scalar](https://user-images.githubusercontent.com/19675068/31562540-393bd6f2-b032-11e7-97f8-52efeecbd8d5.png)
A nicer solution is given by solving the problem with:
```
ebc_1=EssentialBC('ebc1', gamma_1, {'u.all' : 10.0})
ebc_2=EssentialBC('ebc2', gamma_2, {'u.all' : 0.0})
```
![ring_scalar2](https://user-images.githubusercontent.com/19675068/31562694-c11c9138-b032-11e7-8956-937c1e396f3b.png)

**Comment by lbertolotti** [comment]
For problems involving time derivatives we can use:
sfepy.solvers.ts_solvers.SimpleTimeSteppingSolver
Implicit time stepping solver with a fixed time step.
 
Kind: 'ts.simple'
 
For common configuration parameters, see :class:`Solver
<sfepy.solvers.solvers.Solver>`.
 
Specific configuration parameters:
 
Parameters
t0 : float (default: 0.0)
    The initial time.
t1 : float (default: 1.0)
    The final time.
dt : float
    The time step. Used if `n_step` is not given.
n_step : int (default: 10)
    The number of time steps. Has precedence over `dt`.
quasistatic : bool (default: False)
    If True, assume a quasistatic time-stepping. Then the non-linear
    solver is invoked also for the initial time.
**solve_step**(self, ts, state0, nls_status=None)
