### ISSUE TITLE
Missing module when running examples

### ISSUE THREAD

**Issue by yw5aj** [sfepy/sfepy#439]
When I ran the following command I see an error:

```
(sfepy) X:\AbaqusFolder\sfepy>simple.py examples\diffusion\time_poisson_explicit.py

(sfepy) X:\AbaqusFolder\sfepy>python simple.py examples\diffusion\time_poisson_explicit.py
Traceback (most recent call last):
  File "simple.py", line 21, in <module>
    from sfepy.applications import PDESolverApp
  File "X:\AbaqusFolder\sfepy\sfepy\applications\__init__.py", line 3, in <module>
    from .pde_solver_app import PDESolverApp, solve_pde, assign_standard_hooks
  File "X:\AbaqusFolder\sfepy\sfepy\applications\pde_solver_app.py", line 7, in <module>
    from sfepy.discrete import Problem
  File "X:\AbaqusFolder\sfepy\sfepy\discrete\__init__.py", line 9, in <module>
    from .variables import Variables, Variable, FieldVariable, create_adof_conns
  File "X:\AbaqusFolder\sfepy\sfepy\discrete\variables.py", line 14, in <module>
    import sfepy.linalg as la
  File "X:\AbaqusFolder\sfepy\sfepy\linalg\__init__.py", line 2, in <module>
    from .extmods.crcm import rcm, permute_in_place
ModuleNotFoundError: No module named 'sfepy.linalg.extmods.crcm'
```

My environment is Windows 10 64 bit, Python 3.6 64-bit with Anaconda Python installed.

Could you please help?

Thanks,
Shawn

**Comment by yw5aj** [comment]
Ah my bad. I installed through `conda` AND cloned the repo; therefore it is looking for the `crcm.pyd` in the wrong directory.
