### ISSUE TITLE
poisson_short_syntax.py fails with: ImportError: No module named crcm

### ISSUE THREAD

**Issue by yurivict** [sfepy/sfepy#456]
```
$ python2.7 simple.py examples/diffusion/poisson_short_syntax.py
Traceback (most recent call last):
  File "simple.py", line 21, in <module>
    from sfepy.applications import PDESolverApp
  File "/usr/ports/math/py-sfepy/work-py27/sfepy-release_2018.1/sfepy/applications/__init__.py", line 3, in <module>
    from .pde_solver_app import PDESolverApp, solve_pde, assign_standard_hooks
  File "/usr/ports/math/py-sfepy/work-py27/sfepy-release_2018.1/sfepy/applications/pde_solver_app.py", line 7, in <module>
    from sfepy.discrete import Problem
  File "/usr/ports/math/py-sfepy/work-py27/sfepy-release_2018.1/sfepy/discrete/__init__.py", line 9, in <module>
    from .variables import Variables, Variable, FieldVariable, create_adof_conns
  File "/usr/ports/math/py-sfepy/work-py27/sfepy-release_2018.1/sfepy/discrete/variables.py", line 14, in <module>
    import sfepy.linalg as la
  File "/usr/ports/math/py-sfepy/work-py27/sfepy-release_2018.1/sfepy/linalg/__init__.py", line 2, in <module>
    from .extmods.crcm import rcm, permute_in_place
ImportError: No module named crcm
```

**Comment by rc** [comment]
This means that the extension modules were not compiled - try running `python setup.py build_ext --inplace`. Does that help?

**Comment by yurivict** [comment]
> This means that the extension modules were not compiled

It did build and install the crcm module:
```
$ pkg info -l py27-sfepy-2018.1 | grep crcm
	/usr/local/lib/python2.7/site-packages/sfepy/linalg/extmods/crcm.so
```

**Comment by rc** [comment]
I see - you are running the command from the sfepy source directory, right? In that case python looks for the extension modules in that directory, and ignores the system-wide installed version - you need the in-place build.

**Comment by yurivict** [comment]
Even when I change directory to outside of the build directory, the same command (with extra-paths) still fails the same way.

**Comment by rc** [comment]
Strange - does the in-place build (see [1], start with a fresh clone, please) work then?

[1] http://sfepy.org/doc-devel/installation.html#installing-sfepy-from-sources

**Comment by rc** [comment]
Stale issue cleanup.
