### ISSUE TITLE
postproc fails on latest release of mayavi 4.6.2

### ISSUE THREAD

**Issue by krrk** [sfepy/sfepy#466]
When running postproc using mayavi 4.6.2 I get the following output:

```
sfepy: reading mesh [line2, tri3, quad4, tetra4, hexa8] (elbow2.vtk)...
sfepy: ...done in 0.15 s
Exception occurred in traits notification handler.
Please check the log file for details.
Exception occurred in traits notification handler for object: <mayavi.tools.mlab_scene_model.MlabSceneModel object at 0x7fce5d99af10>, trait: activated, old value: <undefined>, new value: True
Traceback (most recent call last):
  File "/home/kieran/.pyenv/versions/sfepy36/lib/python3.6/site-packages/traits-4.6.0-py3.6-linux-x86_64.egg/traits/trait_notifiers.py", line 519, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "/home/kieran/.pyenv/versions/sfepy36/lib/python3.6/site-packages/traits-4.6.0-py3.6-linux-x86_64.egg/traits/trait_notifiers.py", line 482, in dispatch
    handler( *args )
  File "/home/kieran/.pyenv/versions/sfepy36/lib/python3.6/site-packages/sfepy-2018.3+git.05e2667a771736ba91423c672f7b594e040c3f90-py3.6-linux-x86_64.egg/sfepy/postprocess/viewer.py", line 1221, in _post_init
    viewer.render_scene(self.scene, viewer.options)
  File "/home/kieran/.pyenv/versions/sfepy36/lib/python3.6/site-packages/sfepy-2018.3+git.05e2667a771736ba91423c672f7b594e040c3f90-py3.6-linux-x86_64.egg/sfepy/postprocess/viewer.py", line 691, in render_scene
    self.build_mlab_pipeline(**options)
  File "/home/kieran/.pyenv/versions/sfepy36/lib/python3.6/site-packages/sfepy-2018.3+git.05e2667a771736ba91423c672f7b594e040c3f90-py3.6-linux-x86_64.egg/sfepy/postprocess/viewer.py", line 413, in build_mlab_pipeline
    data_ranges = get_data_ranges(source, return_only=True)
  File "/home/kieran/.pyenv/versions/sfepy36/lib/python3.6/site-packages/sfepy-2018.3+git.05e2667a771736ba91423c672f7b594e040c3f90-py3.6-linux-x86_64.egg/sfepy/postprocess/utils.py", line 59, in get_data_ranges
    dm = dataset_manager.DatasetManager(dataset=source.outputs[0])
  File "/home/kieran/.pyenv/versions/sfepy36/lib/python3.6/site-packages/traits-4.6.0-py3.6-linux-x86_64.egg/traits/trait_handlers.py", line 172, in error
    value )
traits.trait_errors.TraitError: The 'dataset' trait of a DatasetManager instance must be a DataSet or None, but a value of <tvtk.tvtk_classes.assign_attribute.AssignAttribute object at 0x7fce5d6166d0> <class 'tvtk.tvtk_classes.assign_attribute.AssignAttribute'> was specified.
```

Downgrading to mayavi 4.6.1 and it seems to work fine.

**Comment by rc** [comment]
Thanks for the report!

BTW. does the #394 problem occur with the 4.6.1? That is, after loading a sequence of VTK files, moving the time step sliders does not change the file displayed.

**Comment by rc** [comment]
I have a fix, this will be closed soon.
