### ISSUE TITLE
AttributeError: 'list' object has no attribute 'rfind'`

### ISSUE THREAD

**Issue by lbertolotti** [sfepy/sfepy#573]
`/usr/lib/python2.7/dist-packages/sfepy$ python setup.py build_ext --inplace
Appending applications configuration to 
Ignoring attempt to set 'name' (from '' to 'applications')
Appending base configuration to
Ignoring attempt to set 'name' (from '' to 'base')
non-existing path in 'discrete/common/extmods': 'fmfield.c'
non-existing path in 'discrete/common/extmods': 'refmaps.c'
non-existing path in 'discrete/common/extmods': 'geommech.c'
non-existing path in 'discrete/common/extmods': 'common_python.c'
non-existing path in 'discrete/common/extmods': 'fmfield.c'
non-existing path in 'discrete/common/extmods': 'refmaps.c'
non-existing path in 'discrete/common/extmods': 'geommech.c'
non-existing path in 'discrete/common/extmods': 'common_python.c'
non-existing path in 'discrete/common/extmods': '_fmfield.pyx'
non-existing path in 'discrete/common/extmods': 'fmfield.c'
non-existing path in 'discrete/common/extmods': 'refmaps.c'
non-existing path in 'discrete/common/extmods': 'geommech.c'
non-existing path in 'discrete/common/extmods': 'common_python.c'
non-existing path in 'discrete/common/extmods': 'mappings.pyx'
non-existing path in 'discrete/common/extmods': 'assemble.pyx'
non-existing path in 'discrete/common/extmods': 'cmesh.pyx'
non-existing path in 'discrete/common/extmods': 'geomtrans.c'
non-existing path in 'discrete/common/extmods': 'mesh.c'
non-existing path in 'discrete/common/extmods': 'meshutils.c'
non-existing path in 'discrete/common/extmods': 'sort.c'
non-existing path in 'discrete/common/extmods': 'common_python.c'
non-existing path in 'discrete/common/extmods': 'fmfield.c'
non-existing path in 'discrete/common/extmods': 'refmaps.c'
non-existing path in 'discrete/common/extmods': 'geommech.c'
non-existing path in 'discrete/common/extmods': 'common_python.c'
non-existing path in 'discrete/common/extmods': 'crefcoors.pyx'
non-existing path in 'discrete/common/extmods': 'refcoors.c'
non-existing path in 'discrete/common/extmods': 'geomtrans.c'
non-existing path in 'discrete/common/extmods': 'mesh.c'
non-existing path in 'discrete/common/extmods': '_geommech.pyx'
Appending discrete.common.extmods configuration to discrete.common
Ignoring attempt to set 'name' (from 'discrete.common' to 'discrete.common.extmods')
Appending discrete.common configuration to discrete
Ignoring attempt to set 'name' (from 'discrete' to 'discrete.common')
non-existing path in 'discrete/fem/extmods': '../../common/extmods/fmfield.c'
non-existing path in 'discrete/fem/extmods': '../../common/extmods/refmaps.c'
non-existing path in 'discrete/fem/extmods': '../../common/extmods/geommech.c'
non-existing path in 'discrete/fem/extmods': '../../common/extmods/common_python.c'
non-existing path in 'discrete/fem/extmods': 'bases.pyx'
non-existing path in 'discrete/fem/extmods': 'lagrange.c'
non-existing path in 'discrete/fem/extmods': '../../common/extmods/fmfield.c'
non-existing path in 'discrete/fem/extmods': '../../common/extmods/refmaps.c'
non-existing path in 'discrete/fem/extmods': '../../common/extmods/geommech.c'
non-existing path in 'discrete/fem/extmods': '../../common/extmods/common_python.c'
non-existing path in 'discrete/fem/extmods': 'lobatto_bases.pyx'
non-existing path in 'discrete/fem/extmods': 'lobatto.c'
non-existing path in 'discrete/fem/extmods': 'lobatto1d.c'
Appending discrete.fem.extmods configuration to discrete.fem
Ignoring attempt to set 'name' (from 'discrete.fem' to 'discrete.fem.extmods')
Appending discrete.fem configuration to discrete
Ignoring attempt to set 'name' (from 'discrete' to 'discrete.fem')
non-existing path in 'discrete/iga/extmods': 'igac.pyx'
non-existing path in 'discrete/iga/extmods': 'nurbs.c'
non-existing path in 'discrete/iga/extmods': '../../common/extmods/fmfield.c'
non-existing path in 'discrete/iga/extmods': '../../common/extmods/geommech.c'
non-existing path in 'discrete/iga/extmods': '../../common/extmods/common_python.c'
non-existing path in 'discrete/iga/extmods': '../../common/extmods/fmfield.c'
non-existing path in 'discrete/iga/extmods': '../../common/extmods/geommech.c'
non-existing path in 'discrete/iga/extmods': '../../common/extmods/common_python.c'
Appending discrete.iga.extmods configuration to discrete.iga
Ignoring attempt to set 'name' (from 'discrete.iga' to 'discrete.iga.extmods')
Appending discrete.iga configuration to discrete
Ignoring attempt to set 'name' (from 'discrete' to 'discrete.iga')
Appending discrete.structural configuration to discrete
Ignoring attempt to set 'name' (from 'discrete' to 'discrete.structural')
Appending discrete configuration to
Ignoring attempt to set 'name' (from '' to 'discrete')
Appending mesh configuration to
Ignoring attempt to set 'name' (from '' to 'mesh')
Appending homogenization configuration to 
Ignoring attempt to set 'name' (from '' to 'homogenization')
non-existing path in 'linalg/extmods': 'crcm.pyx'
non-existing path in 'linalg/extmods': 'rcm.c'
non-existing path in 'linalg/extmods': '../../discrete/common/extmods/common_python.c'
Appending linalg.extmods configuration to linalg
Ignoring attempt to set 'name' (from 'linalg' to 'linalg.extmods')
Appending linalg configuration to
Ignoring attempt to set 'name' (from '' to 'linalg')
Appending mechanics configuration to
Ignoring attempt to set 'name' (from '' to 'mechanics')
Appending optimize configuration to
Ignoring attempt to set 'name' (from '' to 'optimize')
Appending parallel configuration to
Ignoring attempt to set 'name' (from '' to 'parallel')
Appending physics configuration to 
Ignoring attempt to set 'name' (from '' to 'physics')
Appending postprocess configuration to
Ignoring attempt to set 'name' (from '' to 'postprocess')
Appending solvers configuration to
Ignoring attempt to set 'name' (from '' to 'solvers')
non-existing path in 'terms/extmods': '../../discrete/common/extmods/fmfield.c'
non-existing path in 'terms/extmods': '../../discrete/common/extmods/refmaps.c'
non-existing path in 'terms/extmods': '../../discrete/common/extmods/geommech.c'
non-existing path in 'terms/extmods': '../../discrete/common/extmods/common_python.c'
non-existing path in 'terms/extmods': '../../discrete/common/extmods/fmfield.c'
non-existing path in 'terms/extmods': '../../discrete/common/extmods/refmaps.c'
non-existing path in 'terms/extmods': '../../discrete/common/extmods/geommech.c'
non-existing path in 'terms/extmods': '../../discrete/common/extmods/common_python.c'
non-existing path in 'terms/extmods': 'terms.pyx'
Appending terms.extmods configuration to terms
Ignoring attempt to set 'name' (from 'terms' to 'terms.extmods')
Appending terms configuration to
Ignoring attempt to set 'name' (from '' to 'terms')
running build_ext
running build_src
build_src
building library "sfepy_common" sources
building extension "discrete.common.extmods._fmfield" sources
Traceback (most recent call last):
  File "setup.py", line 30, in <module>
    setup(**configuration(top_path='').todict())
  File "/home/lbertolotti/.local/lib/python2.7/site-packages/numpy/distutils/core.py", line 171, in setup
    return old_setup(**new_attr)
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/lbertolotti/.local/lib/python2.7/site-packages/numpy/distutils/command/build_ext.py", line 79, in run
    self.run_command('build_src')
  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/lbertolotti/.local/lib/python2.7/site-packages/numpy/distutils/command/build_src.py", line 148, in run
    self.build_sources()
  File "/home/lbertolotti/.local/lib/python2.7/site-packages/numpy/distutils/command/build_src.py", line 165, in build_sources
    self.build_extension_sources(ext)
  File "/home/lbertolotti/.local/lib/python2.7/site-packages/numpy/distutils/command/build_src.py", line 328, in build_extension_sources
    sources, py_files = self.filter_py_files(sources)
  File "/home/lbertolotti/.local/lib/python2.7/site-packages/numpy/distutils/command/build_src.py", line 388, in filter_py_files
    return self.filter_files(sources, ['.py'])
  File "/home/lbertolotti/.local/lib/python2.7/site-packages/numpy/distutils/command/build_src.py", line 397, in filter_files
    (base, ext) = os.path.splitext(source)
  File "/usr/lib/python2.7/posixpath.py", line 98, in splitext
    return genericpath._splitext(p, sep, altsep, extsep)
  File "/usr/lib/python2.7/genericpath.py", line 99, in _splitext
    sepIndex = p.rfind(sep)
AttributeError: 'list' object has no attribute 'rfind'`

**Comment by rc** [comment]
@lbertolotti `/usr/lib/python2.7/dist-packages/sfepy` seems like a directory of an already installed sfepy package, and not a directory with sfepy source code - you should not build sfepy there.

**Comment by lbertolotti** [comment]
@rc Ok, but what should I do about:
`sfepy-run run_tests
python: can't open file 'run_tests.py': [Errno 2] No such file or directory` ?

**Comment by rc** [comment]
Try the following (in a suitable directory without previous sfepy files):
```
git clone https://github.com/sfepy/sfepy
cd sfepy
pip install --user .
cd ..
sfepy-run run_tests
```
This should work - report, please, any problems. Note that `which sfepy-run` should print `~/.local/bin/sfepy-run` after the steps above.

**Comment by lbertolotti** [comment]
`git clone https://github.com/sfepy/sfepy
Cloning into 'sfepy'...
remote: Enumerating objects: 41080, done.
remote: Total 41080 (delta 0), reused 0 (delta 0), pack-reused 41080
Receiving objects: 100% (41080/41080), 21.52 MiB | 249.00 KiB/s, done.
Resolving deltas: 100% (31408/31408), done.
cd sfepy
pip install --user .
Processing /mnt/c/Users/Avell/Estante_Laptop/4_Informatica/Python/sfepy
Installing collected packages: sfepy
  Running setup.py install for sfepy ... done
Successfully installed sfepy-2019.4+git.8078e3394e4b38d2ee1d00adae34f6b4a7b9089d
cd ..
sfepy-run run_tests
<<< directory: /home/lbertolotti/.local/lib/python2.7/site-packages/sfepy/tests, test files: 105
[1] /home/lbertolotti/.local/lib/python2.7/site-packages/sfepy/tests/test_assembling.py
+++   test_assemble_matrix: ok
+++   test_assemble_matrix_complex: ok
+++   test_assemble_vector: ok
+++   test_assemble_vector_complex: ok
[2] /home/lbertolotti/.local/lib/python2.7/site-packages/sfepy/tests/test_base.py
+++   test_container_add: ok
+++   test_parse_conf: ok
+++   test_resolve_deps: ok
+++   test_struct_add: ok
+++   test_struct_i_add: ok
+++   test_verbose_output: ok
[3] /home/lbertolotti/.local/lib/python2.7/site-packages/sfepy/tests/test_cmesh.py
+++   test_cmesh_counts: ok
+++   test_entity_volumes: ok
[4] /home/lbertolotti/.local/lib/python2.7/site-packages/sfepy/tests/test_conditions.py
+++   test_ebcs: ok
+++   test_epbcs: ok
+++   test_ics: ok
+++   test_save_ebc: ok
[5] /home/lbertolotti/.local/lib/python2.7/site-packages/sfepy/tests/test_domain.py
+++   test_facets: ok
+++   test_refine_2_3: ok
+++   test_refine_2_4: ok
+++   test_refine_3_4: ok
+++   test_refine_3_8: ok
+++   test_refine_hexa: ok
+++   test_refine_tetra: ok
[6] /home/lbertolotti/.local/lib/python2.7/site-packages/sfepy/tests/test_eigenvalue_solvers.py
+++   test_eigenvalue_solvers: ok
[7] /home/lbertolotti/.local/lib/python2.7/site-packages/sfepy/tests/test_elasticity_small_strain.py
+++   test_get_solution: ok
+++   test_linear_terms: ok
[8] /home/lbertolotti/.local/lib/python2.7/site-packages/sfepy/tests/test_fem.py
+++   test_base_functions_delta: ok
+++   test_base_functions_values: ok
[9] /home/lbertolotti/.local/lib/python2.7/site-packages/sfepy/tests/test_functions.py
+++   test_ebc_functions: ok
+++   test_material_functions: ok
+++   test_region_functions: ok
[10] /home/lbertolotti/.local/lib/python2.7/site-packages/sfepy/tests/test_high_level.py
+++   test_solving: ok
+++   test_term_arithmetics: ok
+++   test_term_evaluation: ok
+++   test_variables: ok
[11] /home/lbertolotti/.local/lib/python2.7/site-packages/sfepy/tests/test_homogenization_engine.py
+++   test_chunk_micro: ok
+++   test_dependencies: ok
[12] /home/lbertolotti/.local/lib/python2.7/site-packages/sfepy/tests/test_homogenization_perfusion.py
+++   test_solution: ok
[13] /home/lbertolotti/.local/lib/python2.7/site-packages/sfepy/tests/test_hyperelastic_tlul.py
+++   test_solution: ok
[14] /home/lbertolotti/.local/lib/python2.7/site-packages/sfepy/tests/test_input_acoustics.py
+++   test_input: ok
[15] /home/lbertolotti/.local/lib/python2.7/site-packages/sfepy/tests/test_input_acoustics3d.py
+++   test_input: ok
[16] /home/lbertolotti/.local/lib/python2.7/site-packages/sfepy/tests/test_input_active_fibres.py
+++   test_input: ok
[17] /home/lbertolotti/.local/lib/python2.7/site-packages/sfepy/tests/test_input_balloon.py
warp violation -8.131380e-01 at (iel: 9, iqp: 0)!
warp violation -8.131380e-01 at (iel: 9, iqp: 1)!
warp violation -8.131380e-01 at (iel: 9, iqp: 2)!
warp violation -8.131380e-01 at (iel: 9, iqp: 3)!
warp violation -5.266340e-01 at (iel: 330, iqp: 0)!
warp violation -5.266340e-01 at (iel: 330, iqp: 1)!
warp violation -5.266340e-01 at (iel: 330, iqp: 2)!
warp violation -5.266340e-01 at (iel: 330, iqp: 3)!
warp violation -4.581797e-01 at (iel: 11, iqp: 0)!
warp violation -4.581797e-01 at (iel: 11, iqp: 1)!
warp violation -4.581797e-01 at (iel: 11, iqp: 2)!
warp violation -4.581797e-01 at (iel: 11, iqp: 3)!
warp violation -8.029812e-02 at (iel: 104, iqp: 0)!
warp violation -8.029812e-02 at (iel: 104, iqp: 1)!
warp violation -8.029812e-02 at (iel: 104, iqp: 2)!
warp violation -8.029812e-02 at (iel: 104, iqp: 3)!
warp violation -2.155647e+00 at (iel: 196, iqp: 0)!
warp violation -2.155647e+00 at (iel: 196, iqp: 1)!
warp violation -2.155647e+00 at (iel: 196, iqp: 2)!
warp violation -2.155647e+00 at (iel: 196, iqp: 3)!
warp violation -1.038675e+00 at (iel: 196, iqp: 0)!
warp violation -1.038675e+00 at (iel: 196, iqp: 1)!
warp violation -1.038675e+00 at (iel: 196, iqp: 2)!
warp violation -1.038675e+00 at (iel: 196, iqp: 3)!
+++   test_input: ok
[18] /home/lbertolotti/.local/lib/python2.7/site-packages/sfepy/tests/test_input_biot.py
+++   test_input: ok
[19] /home/lbertolotti/.local/lib/python2.7/site-packages/sfepy/tests/test_input_biot_npbc.py
+++   test_input: ok
[20] /home/lbertolotti/.local/lib/python2.7/site-packages/sfepy/tests/test_input_biot_npbc_lagrange.py
+++   test_input: ok
[21] /home/lbertolotti/.local/lib/python2.7/site-packages/sfepy/tests/test_input_biot_short_syntax.py
+++   test_input: ok
[22] /home/lbertolotti/.local/lib/python2.7/site-packages/sfepy/tests/test_input_boron.py
+++   test_input: ok
[23] /home/lbertolotti/.local/lib/python2.7/site-packages/sfepy/tests/test_input_cube.py
+++   test_input: ok
[24] /home/lbertolotti/.local/lib/python2.7/site-packages/sfepy/tests/test_input_darcy_flow_multicomp.py
+++   test_input: ok
[25] /home/lbertolotti/.local/lib/python2.7/site-packages/sfepy/tests/test_input_elastic_contact_planes.py
+++   test_input: ok
[26] /home/lbertolotti/.local/lib/python2.7/site-packages/sfepy/tests/test_input_elastic_contact_sphere.py
+++   test_input: ok
[27] /home/lbertolotti/.local/lib/python2.7/site-packages/sfepy/tests/test_input_elastic_shifted_periodic.py
+++   test_input: ok
[28] /home/lbertolotti/.local/lib/python2.7/site-packages/sfepy/tests/test_input_elastodynamic.py
+++   test_input: ok
[29] /home/lbertolotti/.local/lib/python2.7/site-packages/sfepy/tests/test_input_hydrogen.py
+++   test_input: ok
[30] /home/lbertolotti/.local/lib/python2.7/site-packages/sfepy/tests/test_input_its2D_2.py
+++   test_input: ok
[31] /home/lbertolotti/.local/lib/python2.7/site-packages/sfepy/tests/test_input_laplace_1d.py
+++   test_input: ok
[32] /home/lbertolotti/.local/lib/python2.7/site-packages/sfepy/tests/test_input_laplace_coupling_lcbcs.py
+++   test_input: ok
[33] /home/lbertolotti/.local/lib/python2.7/site-packages/sfepy/tests/test_input_laplace_time_ebcs.py
+++   test_input: ok
[34] /home/lbertolotti/.local/lib/python2.7/site-packages/sfepy/tests/test_input_linear_elastic.py
+++   test_input: ok
[35] /home/lbertolotti/.local/lib/python2.7/site-packages/sfepy/tests/test_input_linear_elastic_damping.py
+++   test_input: ok
[36] /home/lbertolotti/.local/lib/python2.7/site-packages/sfepy/tests/test_input_linear_elastic_iga.py
+++   test_dummy: ok
[37] /home/lbertolotti/.local/lib/python2.7/site-packages/sfepy/tests/test_input_linear_elastic_mM.py
+++   test_input: ok
[38] /home/lbertolotti/.local/lib/python2.7/site-packages/sfepy/tests/test_input_linear_elastic_probes.py
+++   test_input: ok
[39] /home/lbertolotti/.local/lib/python2.7/site-packages/sfepy/tests/test_input_linear_elastic_tractions.py
+++   test_input: ok
[40] /home/lbertolotti/.local/lib/python2.7/site-packages/sfepy/tests/test_input_linear_elastic_up.py
+++   test_input: ok
[41] /home/lbertolotti/.local/lib/python2.7/site-packages/sfepy/tests/test_input_linear_viscoelastic.py
+++   test_input: ok
[42] /home/lbertolotti/.local/lib/python2.7/site-packages/sfepy/tests/test_input_material_nonlinearity.py
+++   test_input: ok
[43] /home/lbertolotti/.local/lib/python2.7/site-packages/sfepy/tests/test_input_navier_stokes.py
+++   test_input: ok
[44] /home/lbertolotti/.local/lib/python2.7/site-packages/sfepy/tests/test_input_navier_stokes2d.py
+++   test_input: ok
[45] /home/lbertolotti/.local/lib/python2.7/site-packages/sfepy/tests/test_input_navier_stokes2d_iga.py
+++   test_dummy: ok
[46] /home/lbertolotti/.local/lib/python2.7/site-packages/sfepy/tests/test_input_nodal_lcbcs.py
---   test_input: failed!
[47] /home/lbertolotti/.local/lib/python2.7/site-packages/sfepy/tests/test_input_oscillator.py
+++   test_input: ok
[48] /home/lbertolotti/.local/lib/python2.7/site-packages/sfepy/tests/test_input_perfusion_tl.py
+++   test_input: ok
[49] /home/lbertolotti/.local/lib/python2.7/site-packages/sfepy/tests/test_input_piezo_elasticity.py
+++   test_ebc: ok
+++   test_input: ok
[50] /home/lbertolotti/.local/lib/python2.7/site-packages/sfepy/tests/test_input_poisson.py
+++   test_input: ok
[51] /home/lbertolotti/.local/lib/python2.7/site-packages/sfepy/tests/test_input_poisson_field_dependent_material.py
+++   test_input: ok
[52] /home/lbertolotti/.local/lib/python2.7/site-packages/sfepy/tests/test_input_poisson_functions.py
+++   test_input: ok
[53] /home/lbertolotti/.local/lib/python2.7/site-packages/sfepy/tests/test_input_poisson_iga.py
+++   test_dummy: ok
[54] /home/lbertolotti/.local/lib/python2.7/site-packages/sfepy/tests/test_input_poisson_neumann.py
+++   test_input: ok
[55] /home/lbertolotti/.local/lib/python2.7/site-packages/sfepy/tests/test_input_poisson_periodic_boundary_condition.py
+++   test_input: ok
[56] /home/lbertolotti/.local/lib/python2.7/site-packages/sfepy/tests/test_input_prestress_fibres.py
+++   test_input: ok
[57] /home/lbertolotti/.local/lib/python2.7/site-packages/sfepy/tests/test_input_shell10x_cantilever.py
+++   test_input: ok
[58] /home/lbertolotti/.local/lib/python2.7/site-packages/sfepy/tests/test_input_sinbc.py
+++   test_input: ok
[59] /home/lbertolotti/.local/lib/python2.7/site-packages/sfepy/tests/test_input_stabilized_navier_stokes.py
+++   test_input: ok
[60] /home/lbertolotti/.local/lib/python2.7/site-packages/sfepy/tests/test_input_stokes.py
+++   test_input: ok
[61] /home/lbertolotti/.local/lib/python2.7/site-packages/sfepy/tests/test_input_stokes_slip_bc.py
+++   test_input: ok
[62] /home/lbertolotti/.local/lib/python2.7/site-packages/sfepy/tests/test_input_stokes_slip_bc_penalty.py
+++   test_input: ok
[63] /home/lbertolotti/.local/lib/python2.7/site-packages/sfepy/tests/test_input_thermo_elasticity.py
+++   test_input: ok
[64] /home/lbertolotti/.local/lib/python2.7/site-packages/sfepy/tests/test_input_thermo_elasticity_ess.py
+++   test_input: ok
[65] /home/lbertolotti/.local/lib/python2.7/site-packages/sfepy/tests/test_input_time_advection_diffusion.py
+++   test_input: ok
[66] /home/lbertolotti/.local/lib/python2.7/site-packages/sfepy/tests/test_input_time_poisson.py
+++   test_input: ok
[67] /home/lbertolotti/.local/lib/python2.7/site-packages/sfepy/tests/test_input_two_bodies_contact.py
+++   test_input: ok
[68] /home/lbertolotti/.local/lib/python2.7/site-packages/sfepy/tests/test_input_vibro_acoustic3d.py
+++   test_input: ok
[69] /home/lbertolotti/.local/lib/python2.7/site-packages/sfepy/tests/test_input_well.py
+++   test_input: ok
[70] /home/lbertolotti/.local/lib/python2.7/site-packages/sfepy/tests/test_io.py
+++   test_recursive_dict_hdf5: ok
+++   test_sparse_matrix_hdf5: ok
[71] /home/lbertolotti/.local/lib/python2.7/site-packages/sfepy/tests/test_laplace_unit_disk.py
+++   test_boundary_fluxes: ok
[72] /home/lbertolotti/.local/lib/python2.7/site-packages/sfepy/tests/test_laplace_unit_square.py
+++   test_boundary_fluxes: ok
+++   test_solution: ok
[73] /home/lbertolotti/.local/lib/python2.7/site-packages/sfepy/tests/test_lcbc_2d.py
+++   test_linear_rigid_body_bc: ok
[74] /home/lbertolotti/.local/lib/python2.7/site-packages/sfepy/tests/test_lcbc_3d.py
+++   test_linear_rigid_body_bc: ok
[75] /home/lbertolotti/.local/lib/python2.7/site-packages/sfepy/tests/test_lcbcs.py
+++   test_laplace_shifted_periodic: ok
+++   test_stokes_slip_bc: ok
[76] /home/lbertolotti/.local/lib/python2.7/site-packages/sfepy/tests/test_linalg.py
+++   test_assemble1d: ok
+++   test_geometry: ok
+++   test_tensors: ok
+++   test_unique_rows: ok
[77] /home/lbertolotti/.local/lib/python2.7/site-packages/sfepy/tests/test_linear_solvers.py
+++   test_ls_reuse: ok
+++   test_solvers: ok
[78] /home/lbertolotti/.local/lib/python2.7/site-packages/sfepy/tests/test_linearization.py
+++   test_linearization: ok
[79] /home/lbertolotti/.local/lib/python2.7/site-packages/sfepy/tests/test_log.py
+++   test_log_create: ok
+++   test_log_rw: ok
[80] /home/lbertolotti/.local/lib/python2.7/site-packages/sfepy/tests/test_matcoefs.py
---   test_conversion_functions: failed!
---   test_elastic_constants: failed!
+++   test_stiffness_tensors: ok
[81] /home/lbertolotti/.local/lib/python2.7/site-packages/sfepy/tests/test_mesh_expand.py
+++   test_mesh_expand: ok
[82] /home/lbertolotti/.local/lib/python2.7/site-packages/sfepy/tests/test_mesh_generators.py
+++   test_gen_block_mesh: ok
+++   test_gen_cylinder_mesh: ok
+++   test_gen_extended_block_mesh: ok
+++   test_gen_mesh_from_geom: ok
+++   test_gen_mesh_from_voxels: ok
+++   test_gen_tiled_mesh: ok
[83] /home/lbertolotti/.local/lib/python2.7/site-packages/sfepy/tests/test_mesh_interp.py
+++   test_evaluate_at: ok
+++   test_field_gradient: ok
+++   test_interpolation: ok
+++   test_interpolation_two_meshes: ok
+++   test_invariance: ok
+++   test_invariance_qp: ok
[84] /home/lbertolotti/.local/lib/python2.7/site-packages/sfepy/tests/test_mesh_smoothing.py
+++   test_mesh_smoothing: ok
[85] /home/lbertolotti/.local/lib/python2.7/site-packages/sfepy/tests/test_meshio.py
+++   test_read_meshes: ok
+++   test_compare_same_meshes: ok
+++   test_read_dimension: ok
+++   test_write_read_meshes: ok
+++   test_hdf5_meshio: ok
[86] /home/lbertolotti/.local/lib/python2.7/site-packages/sfepy/tests/test_msm_laplace.py
+++   test_msm_laplace: ok
[87] /home/lbertolotti/.local/lib/python2.7/site-packages/sfepy/tests/test_msm_symbolic.py
+++   test_msm_symbolic_diffusion: ok
+++   test_msm_symbolic_laplace: ok
[88] /home/lbertolotti/.local/lib/python2.7/site-packages/sfepy/tests/test_normals.py
+++   test_normals: ok
[89] /home/lbertolotti/.local/lib/python2.7/site-packages/sfepy/tests/test_parsing.py
+++   test_parse_equations: ok
+++   test_parse_regions: ok
[90] /home/lbertolotti/.local/lib/python2.7/site-packages/sfepy/tests/test_periodic_bc_2d.py
+++   test_pbc: ok
[91] /home/lbertolotti/.local/lib/python2.7/site-packages/sfepy/tests/test_periodic_bc_3d.py
+++   test_pbc: ok
[92] /home/lbertolotti/.local/lib/python2.7/site-packages/sfepy/tests/test_poly_spaces.py
+++   test_continuity: ok
+++   test_gradients: ok
+++   test_hessians: ok
[93] /home/lbertolotti/.local/lib/python2.7/site-packages/sfepy/tests/test_projections.py
+++   test_mass_matrix: ok
+++   test_project_tensors: ok
+++   test_projection_iga_fem: ok
+++   test_projection_tri_quad: ok
[94] /home/lbertolotti/.local/lib/python2.7/site-packages/sfepy/tests/test_quadratures.py
+++   test_quadratures: ok
+++   test_weight_consistency: ok
[95] /home/lbertolotti/.local/lib/python2.7/site-packages/sfepy/tests/test_ref_coors.py
+++   test_ref_coors_fem: ok
+++   test_ref_coors_iga: ok
[96] /home/lbertolotti/.local/lib/python2.7/site-packages/sfepy/tests/test_refine_hanging.py
+++   test_continuity: ok
+++   test_preserve_coarse_entities: ok
[97] /home/lbertolotti/.local/lib/python2.7/site-packages/sfepy/tests/test_regions.py
+++   test_operators: ok
+++   test_selectors: ok
[98] /home/lbertolotti/.local/lib/python2.7/site-packages/sfepy/tests/test_semismooth_newton.py
---   test instance creation failed
[99] /home/lbertolotti/.local/lib/python2.7/site-packages/sfepy/tests/test_sparse.py
+++   test_compose_sparse: ok
[100] /home/lbertolotti/.local/lib/python2.7/site-packages/sfepy/tests/test_splinebox.py
+++   test_spbox_2d: ok
+++   test_spbox_3d: ok
+++   test_spbox_field: ok
+++   test_spregion2d: ok
[101] /home/lbertolotti/.local/lib/python2.7/site-packages/sfepy/tests/test_tensors.py
+++   test_stress_transform: ok
+++   test_tensors: ok
+++   test_transform_data: ok
+++   test_transform_data4: ok
[102] /home/lbertolotti/.local/lib/python2.7/site-packages/sfepy/tests/test_term_call_modes.py
+++   test_term_call_modes: ok
[103] /home/lbertolotti/.local/lib/python2.7/site-packages/sfepy/tests/test_term_consistency.py
+++   test_consistency_d_dw: ok
+++   test_ev_div: ok
+++   test_ev_grad: ok
+++   test_eval_matrix: ok
+++   test_surface_evaluate: ok
+++   test_vector_matrix: ok
[104] /home/lbertolotti/.local/lib/python2.7/site-packages/sfepy/tests/test_units.py
+++   test_consistent_sets: ok
+++   test_units: ok
[105] /home/lbertolotti/.local/lib/python2.7/site-packages/sfepy/tests/test_volume.py
+++   test_volume: ok
+++   test_volume_tl: ok
105 test file(s) executed in 282.34 s, 4 failure(s) of 180 test(s)
which sfepy-run
/home/lbertolotti/.local/bin/sfepy-run      `

**Comment by lbertolotti** [comment]
Ok, should we assume `sudo apt-get install python-sfepy` is not working?

**Comment by rc** [comment]
It looks so - it seems that the `sfepy.top_dir variable` is not set correctly. Note that the python-sfepy package is not provided/maintained by people involved in sfepy development.

**Comment by rc** [comment]
Closing old issues...
