### ISSUE TITLE
error during using save_image()

### ISSUE THREAD

**Issue by Yuanzhi0202** [sfepy/sfepy#653]
I want save a snapshot of a vtk file in viewer mode (I have set 

filename = xxx.vtk
view = Viewer(filename, output_dir='...')
view(vector_mode='warp_norm', is_wireframe=True, rel_scaling=0.01,
         filter_names=[....], is_scalar_bar=True, opacity=1)

then I code like:
 view.save_image(filename='xxx')

That is what I get:
         Traceback (most recent call last):
  File "....", line ...
    view.save_image(filename='xxx')
  File "...\sfepy\postprocess\viewer.py", line 294, in save_image
    self.scene.scene.save(name)
  File "...tvtk\pyface\scene_model.py", line 181, in save
    self.scene_editor.save(file_name, size, **kw_args)
  File "....tvtk\pyface\tvtk_scene.py", line 421, in save
    raise ValueError(
ValueError: Unable to find suitable image type for given file extension.

How can I fix it? Or is there any other way to save a snapshot for a vtk file? (code-only method needed, no operation in mayavi)

**Comment by Yuanzhi0202** [comment]
Thx that works！
