### ISSUE TITLE
Best practice to define local coordinate for orthotropic material

### ISSUE THREAD

**Issue by Kang-SungKu** [sfepy/sfepy#804]
Hello,

I am trying SfePy to simulate the mechanical behavior of lumber pieces, specifically to calculate stress/strain under bending as shown below.
![image](https://user-images.githubusercontent.com/17635416/162838534-9d28b6e5-b9f8-44bc-9c93-b0c8a1b36f7c.png)

To make the simulation realistic, there are two requirements: 1) model the knot (local vulnerability, top-left of the attached figure) and 2) make the material align with the fiber direction (top-right of the attached figure). For the first requirement, I could implement by having subdomains defined with custom function, and assign different material properties to different domains. However, I am not sure what would be the best practice for the second requirement.

My expectation is that I can set up orthotropic material property, and use custom function (representing the flow of fiber across the domain) to assign local coordinate at each node. I could find some examples of composite material (bulk material + fiber within), but could not find an example of defining local coordinate of orthotropic material (bulky material but have local material alignment like a lumber piece).

I am attaching my code below where I use `dw_lin_elastic` + postprocessing to calculate stress/strain across the domain. Can you let me know what is the best practice to define local coordinate for orthotropic material? Can I still use `dw_lin_elastic` or need to use a different method?

I appreciate your time and help!

```
    regions.update({
        'Omega': 'all',
        'Omega_knot': ('cells by get_knot_region', 'cell'),
        'Omega_deviation_filled': ('cells by get_fiber_deviation_region', 'cell'),
        'Omega_transition_filled': ('cells by get_transition_region', 'cell'),
        'Omega_deviation': ('r.Omega_deviation_filled -c r.Omega_knot', 'cell'),
        'Omega_transition': ('r.Omega_transition_filled -c r.Omega_deviation_filled', 'cell'),
        'Omega_clean': ('all -c r.Omega_transition_filled', 'cell'),
        'LeftBottom': ('vertices in (x < {}) & (y < {})'.format(-dims[0]/2 + 1.5*ddims[0], -dims[1]/2 + 1.5*ddims[1]), 'facet'),
        'RightBottom': ('vertices in (x > {}) & (y < {})'.format(dims[0]/2 - 1.5*ddims[0], -dims[1]/2 + 1.5*ddims[1]), 'facet'),
        'CenterTop': ('vertices in (x < {}) & (x > {}) & (y > {})'.format(1.5*ddims[0], -1.5*ddims[0], dims[1]/2 - 1.5*ddims[1]), 'facet'),
    })

    fields = {
        'displacement': ('real', 'vector', 'Omega', 1),
    }

    # These are the functions used to define sub-domains.
    functions = {
        'get_knot_region': (get_knot_region,),
        'get_fiber_deviation_region': (get_fiber_deviation_region,),
        'get_transition_region': (get_transition_region,),
    }

    variables = {
        'u': ('unknown field', 'displacement', 0),
        'v': ('test field', 'displacement', 'u'),
    }

    young = 8000.0  # Young's modulus [MPa]
    poisson = 0.4  # Poisson's ratio
    ratio_transition = 0.7
    ratio_deviation = 0.35
    ratio_knot = 0.05
    stiffness_timber_clean = stiffness_from_youngpoisson(dim=3, young=young, poisson=poisson)
    stiffness_timber_transition = stiffness_from_youngpoisson(dim=3, young=young*ratio_transition, poisson=poisson)
    stiffness_timber_deviation = stiffness_from_youngpoisson(dim=3, young=young*ratio_deviation, poisson=poisson)
    stiffness_timber_knot = stiffness_from_youngpoisson(dim=3, young=young*ratio_knot, poisson=poisson)
    materials = {
        'timber': ({'D': {
            'Omega_clean': stiffness_timber_clean,
            'Omega_transition': stiffness_timber_transition,
            'Omega_deviation': stiffness_timber_deviation,
            'Omega_knot': stiffness_timber_knot}
                   },),
        'load': ({'.val': [0.0, -10000.0, 0.0]},),
    }

    ebcs = {
        'XiSym': ('LeftBottom', {'u.all': 0.0}),
        'XfSym': ('RightBottom', {'u.all': 0.0}),
    }

    integrals = {
        'i': 2,
    }

    equations = {
        'balance_of_forces': "dw_lin_elastic.2.Omega(timber.D, v, u)"
                             "= dw_point_load.0.CenterTop(load.val, v)",
    }

    solvers = {
        'ls': ('ls.scipy_direct', {}),
        'newton': ('nls.newton',
                   {'i_max': 1,
                    'eps_a': 1e-10,
                    }),
    }

    output_dir = '.'  # set this to a valid directory you have write access to
    options = {
        'output_dir': output_dir,
    }

    # Post-processing
    def stress_strain(out, pb, state, extend=False):
        """
        Calculate and output strain and stress for given displacements.
        """
        from sfepy.base.base import Struct
        ev = pb.evaluate
        strain = ev('ev_cauchy_strain.2.Omega(u)', mode='el_avg')
        stress = ev('ev_cauchy_stress.2.Omega(timber.D, u)', mode='el_avg', copy_materials=False)

        out['cauchy_strain'] = Struct(name='output_data', mode='cell', data=strain, dofs=None)
        out['cauchy_stress'] = Struct(name='output_data', mode='cell', data=stress, dofs=None)
        return out

    timber = materials['timber'][0]
    timber.update(
        {'D': {
            'Omega_clean': stiffness_timber_clean,
            'Omega_transition': stiffness_timber_transition,
            'Omega_deviation': stiffness_timber_deviation,
            'Omega_knot': stiffness_timber_knot}
         }
    )
    options.update({'post_process_hook': 'stress_strain', })

```

**Comment by rc** [comment]
You could define the elastic tensor D (aligned with coordinate axes), as [shown here](https://en.wikipedia.org/wiki/Orthotropic_material#Stiffness_and_compliance_matrices_in_orthotropic_elasticity) and then use [transform_data()](https://sfepy.org/doc-devel/src/sfepy/mechanics/tensors.html?highlight=transform_data#sfepy.mechanics.tensors.transform_data) to transform it to local coordinate frames in a [material definition function](https://sfepy.org/doc-devel/users_guide.html#defining-material-parameters-by-functions) returning D for `dw_lin_elastic`. There is no other support  - the coordinate transformation matrices need to be provided.

**Comment by Kang-SungKu** [comment]
I appreciate your response. Can you let me know how to use use material definition function for different regions? I tried the followings but did not work.

 - Trial 1: Use different functions for different regions --> Could not convert string to float
```
    materials = {
        'timber': ({'D': {
            'Omega_clean': 'get_aligned_stiffness_clean',
            'Omega_transition': 'get_aligned_stiffness_transition',
            'Omega_deviation': 'get_aligned_stiffness_deviation',
            'Omega_knot': 'get_aligned_stiffness_knot'}
                   },),
        'load': ({'.val': [0.0, -10000.0, 0.0]},),
    }

```

- Log from Trial 1

```
sfepy: dims: (600, 100, 200), shape: (72, 12, 24), u_order: 1, refine: 0, u_inlet: None
sfepy: linear solver: ls_d
sfepy: mode: lcbc, term_mode: original
sfepy: left over: ['stress_strain', 'output_dir', 'equations', 'get_aligned_stiffness_knot', 'get_aligned_stiffness_deviation', 'get_aligned_stiffness_transition', 'get_aligned_stiffness_clean', 'ratio_knot', 'ratio_deviation', 'rat
io_transition', 'poisson', 'young', 'ddims', 'get_transition_region', 'get_fiber_deviation_region', 'get_knot_region', 'mesh_hook', 'verbosity', 'optimize', 'backend', 'term_mode', 'mode', 'u_inlet', 'ls', 'refine', 'u_order', 'stif
fness_timber_transition', 'stiffness_timber_knot', 'stiffness_timber_deviation', 'stiffness_timber_clean', 'shape', 'list_knot', 'get_transform_matrix', 'get_cone_region', 'get_aligned_material_parameters', 'dims', 'dict_flow', 'verbose', '_filename']
sfepy: reading mesh [user] (function:mesh_hook)...
sfepy: ...done in 0.00 s
sfepy: creating regions...
sfepy:     Near
sfepy:     Far
sfepy:     Bottom
sfepy:     Top
sfepy:     Left
sfepy:     Right
sfepy:     Corners
sfepy:     Omega
sfepy:     Omega_knot
sfepy:     Omega_deviation_filled
sfepy:     Omega_transition_filled
sfepy:     LeftBottom
sfepy:     RightBottom
sfepy:     CenterTop
sfepy:     Omega_deviation
sfepy:     Omega_transition
sfepy:     Omega_clean
sfepy: ...done in 0.06 s
sfepy: equation "balance_of_forces":
sfepy: dw_lin_elastic.2.Omega(timber.D, v, u) = dw_point_load.0.CenterTop(load.val, v)
sfepy: using solvers:
                ts: no ts
               nls: newton
                ls: ls
sfepy: updating variables...
sfepy: ...done
sfepy: setting up dof connectivities...
sfepy: ...done in 0.00 s
sfepy: matrix shape: (61632, 61632)
sfepy: assembling matrix graph...
sfepy: ...done in 0.24 s
sfepy: matrix structural nonzeros: 4541040 (-9.15e-03% fill)
sfepy: updating variables...
sfepy: ...done
sfepy: updating materials...
    verbose=verbose)
  File "C:\ProgramData\Miniconda3\envs\AdvancedTimberManufacturing\lib\site-packages\sfepy\discrete\materials.py", line 58, in time_update
    mat.time_update(ts, equations, mode=mode, problem=problem)
  File "C:\ProgramData\Miniconda3\envs\AdvancedTimberManufacturing\lib\site-packages\sfepy\discrete\materials.py", line 303, in time_update
    self.update_data(key, ts, equations, term, problem=problem)
  File "C:\ProgramData\Miniconda3\envs\AdvancedTimberManufacturing\lib\site-packages\sfepy\discrete\materials.py", line 220, in update_data
    **self.extra_args)
  File "C:\ProgramData\Miniconda3\envs\AdvancedTimberManufacturing\lib\site-packages\sfepy\discrete\functions.py", line 37, in __call__
    return self.function(*args, **_kwargs)
  File "C:\ProgramData\Miniconda3\envs\AdvancedTimberManufacturing\lib\site-packages\sfepy\discrete\functions.py", line 165, in get_constants
    rval = nm.array(rval, dtype=dtype, ndmin=3)
ValueError: could not convert string to float: 'get_aligned_stiffness_clean'

```


- Trial 2: Use a single material definition returning different 'D' for different regions --> different regions are not recognized
```
    materials = {
        'timber': 'get_aligned_timber_stiffness',
        'load': ({'.val': [0.0, -10000.0, 0.0]},),
    }

    def get_aligned_timber_stiffness(ts, coors, mode=None, **kwargs):
        if mode != 'qp':
            return
        out = {}
        out['D'] = {}
        out['D']['Omega_clean'] = np.tile(stiffness_timber_clean, (coors.shape[0], 1, 1))
        out['D']['Omega_transition'] = np.tile(stiffness_timber_clean, (coors.shape[0], 1, 1))
        out['D']['Omega_deviation'] = np.tile(stiffness_timber_clean, (coors.shape[0], 1, 1))
        out['D']['Omega_knot'] = np.tile(stiffness_timber_clean, (coors.shape[0], 1, 1))
        return out

```

- Log from Trial 2
```
sfepy: dims: (600, 100, 200), shape: (72, 12, 24), u_order: 1, refine: 0, u_inlet: None
sfepy: linear solver: ls_d
sfepy: mode: lcbc, term_mode: original
sfepy: left over: ['stress_strain', 'output_dir', 'equations', 'get_aligned_stiffness_knot', 'get_aligned_stiffness_deviation', 'get_aligned_stiffness_transition', 'get_aligned_stiffness_clean', 'get_aligned_timber_stiffness', 'rati
o_knot', 'ratio_deviation', 'ratio_transition', 'poisson', 'young', 'ddims', 'get_transition_region', 'get_fiber_deviation_region', 'get_knot_region', 'mesh_hook', 'verbosity', 'optimize', 'backend', 'term_mode', 'mode', 'u_inlet', 
'ls', 'refine', 'u_order', 'stiffness_timber_transition', 'stiffness_timber_knot', 'stiffness_timber_deviation', 'stiffness_timber_clean', 'shape', 'list_knot', 'get_transform_matrix', 'get_cone_region', 'get_aligned_material_parameters', 'dims', 'dict_flow', 'verbose', '_filename']
sfepy: reading mesh [user] (function:mesh_hook)...
sfepy: ...done in 0.00 s
sfepy: creating regions...
sfepy:     Near
sfepy:     Far
sfepy:     Bottom
sfepy:     Top
sfepy:     Left
sfepy:     Right
sfepy:     Corners
sfepy:     Omega
sfepy:     Omega_knot
sfepy:     Omega_deviation_filled
sfepy:     Omega_transition_filled
sfepy:     LeftBottom
sfepy:     RightBottom
sfepy:     CenterTop
sfepy:     Omega_deviation
sfepy:     Omega_transition
sfepy:     Omega_clean
sfepy: ...done in 0.07 s
sfepy: equation "balance_of_forces":
sfepy: dw_lin_elastic.2.Omega(timber.D, v, u) = dw_point_load.0.CenterTop(load.val, v)
sfepy: using solvers:
                ts: no ts
               nls: newton
                ls: ls
sfepy: updating variables...
sfepy: ...done
sfepy: setting up dof connectivities...
sfepy: ...done in 0.01 s
sfepy: matrix shape: (61632, 61632)
sfepy: assembling matrix graph...
sfepy: ...done in 0.28 s
sfepy: matrix structural nonzeros: 4541040 (-9.15e-03% fill)
sfepy: updating variables...
sfepy: ...done
sfepy: updating materials...
sfepy:     timber
Traceback (most recent call last):
  File "./simple.py", line 190, in <module>
    main()
    mat.time_update(ts, equations, mode=mode, problem=problem)
  File "C:\ProgramData\Miniconda3\envs\AdvancedTimberManufacturing\lib\site-packages\sfepy\discrete\materials.py", line 303, in time_update
    self.update_data(key, ts, equations, term, problem=problem)
  File "C:\ProgramData\Miniconda3\envs\AdvancedTimberManufacturing\lib\site-packages\sfepy\discrete\materials.py", line 222, in update_data
    self.set_data(key, qps, data)
  File "C:\ProgramData\Miniconda3\envs\AdvancedTimberManufacturing\lib\site-packages\sfepy\discrete\materials.py", line 189, in set_data
    if val.ndim != 3:
AttributeError: 'dict' object has no attribute 'ndim'

```

**Comment by Kang-SungKu** [comment]
https://github.com/sfepy/sfepy/issues/796#issuecomment-1092679502

This seems to related to the same question (using multiple material definition functions for multiple regions). I will look into this!

**Comment by Kang-SungKu** [comment]
For those who have similar needs, this is my approach to use multiple material definition functions for multiple (disjoint) regions --> to modify the equation to combine the terms for different regions/materials.

```
    # Functions defining (disjoint) regions and material definition functions
    functions = {
        # Functions defining disjoint sub-regions under Omega: Omega_knot, Omega_deviation, Omega_transition --> rest: Omega_clean
        'get_knot_region':
            (lambda coors, domain: get_cone_region(coors, domain),),
        'get_fiber_deviation_region':
            (lambda coors, domain: get_cone_region(coors, domain, double_cone_info={'n_fold': 6, 'gap': 25}),),
        'get_transition_region':
            (lambda coors, domain: get_cone_region(coors, domain, double_cone_info={'n_fold': 7, 'gap': 40}),),
        # Functions defining elastic tensors for different regions
        'get_aligned_elastic_tensor_clean':
            (lambda ts, coors, mode, **kwargs:
             get_aligned_elastic_tensor(ts, coors, mode, elastic_tensor_org=stiffness_timber_clean, **kwargs),),
        'get_aligned_elastic_tensor_transition':
            (lambda ts, coors, mode, **kwargs:
             get_aligned_elastic_tensor(ts, coors, mode, elastic_tensor_org=stiffness_timber_transition, **kwargs),),
        'get_aligned_elastic_tensor_deviation':
            (lambda ts, coors, mode, **kwargs:
             get_aligned_elastic_tensor(ts, coors, mode, elastic_tensor_org=stiffness_timber_deviation, **kwargs),),
        'get_aligned_elastic_tensor_knot':
            (lambda ts, coors, mode, **kwargs:
             get_aligned_elastic_tensor(ts, coors, mode, elastic_tensor_org=stiffness_timber_knot, **kwargs),),
    }

    # Regions
    regions.update({
        'Omega': 'all',
        'Omega_knot': ('cells by get_knot_region', 'cell'),
        'Omega_deviation_filled': ('cells by get_fiber_deviation_region', 'cell'),
        'Omega_transition_filled': ('cells by get_transition_region', 'cell'),
        'Omega_deviation': ('r.Omega_deviation_filled -c r.Omega_knot', 'cell'),
        'Omega_transition': ('r.Omega_transition_filled -c r.Omega_deviation_filled', 'cell'),
        'Omega_clean': ('all -c r.Omega_transition_filled', 'cell'),
        'LeftBottom': ('vertices in (x < {}) & (y < {})'.format(-dims[0]/2 + 1.5*ddims[0], -dims[1]/2 + 1.5*ddims[1]), 'facet'),
        'RightBottom': ('vertices in (x > {}) & (y < {})'.format(dims[0]/2 - 1.5*ddims[0], -dims[1]/2 + 1.5*ddims[1]), 'facet'),
        'CenterTop': ('vertices in (x < {}) & (x > {}) & (y > {})'.format(1.5*ddims[0], -1.5*ddims[0], dims[1]/2 - 1.5*ddims[1]), 'facet'),
    })

    # Material definition function is assigned to each material
    materials = {
        'timber_clean': 'get_aligned_elastic_tensor_clean',
        'timber_knot': 'get_aligned_elastic_tensor_knot',
        'timber_transition': 'get_aligned_elastic_tensor_transition',
        'timber_deviation': 'get_aligned_elastic_tensor_deviation',
        'load': ({'.val': [0.0, -10000.0, 0.0]},),
    }

    # Equation combining disjoint regions
    equations = {
        'balance_of_forces':
            "dw_lin_elastic.2.Omega_clean(timber_clean.D, v, u) +"
            "dw_lin_elastic.2.Omega_transition(timber_transition.D, v, u) +"
            "dw_lin_elastic.2.Omega_deviation(timber_deviation.D, v, u) +"
            "dw_lin_elastic.2.Omega_knot(timber_knot.D, v, u)"
            "= dw_point_load.0.CenterTop(load.val, v)",
    }

```

One thing I am still not sure is how to evaluate stress across the entire region, using different materials for different subregions. Just combining the terms, similar to how I modified equation as shown below, did not work. Any suggestion would be appreciated!
```
    def stress_strain(out, pb, state, extend=False):
        """
        Calculate and output strain and stress for given displacements.
        """
        from sfepy.base.base import Struct
        ev = pb.evaluate
        strain = ev('ev_cauchy_strain.2.Omega(u)', mode='el_avg')

        # Note: the following did not work
        #stress = ev('ev_cauchy_stress.2.Omega_clean(timber_clean.D, u) + ev_cauchy_stress.2.Omega_knot(timber_knot.D, u)', mode='el_avg', copy_materials=False)

        out['cauchy_strain'] = Struct(name='output_data', mode='cell', data=strain, dofs=None)
        #out['cauchy_stress'] = Struct(name='output_data', mode='cell', data=stress, dofs=None)
        return out

```

**Comment by rc** [comment]
Glad you solved your problem. Some notes:

-  You might be able to define a single material function, as the integral region is one of the material function parameters.
- It might be even possible to combine the region selection functions with the material one, and define the parameters based on the quadrature point coordinates. Then you would have a single region/material/function.
- Having a single region/material/function, you should be able to evaluate the stress across the entire domain using a single term.
