### ISSUE TITLE
Broken band_gaps*.py examples

### ISSUE THREAD

**Issue by vlukes** [sfepy/sfepy#808]
The following examples seem to be broken:

- examples/phononic/band_gaps.py
- examples/phononic/band_gaps_rigid.py

Even if the multiprocessing is off.

**Comment by rc** [comment]
They work for me, but the figures (`-p` option) look weird. What error do you get?

**Comment by vlukes** [comment]
e.g. examples/phononic/band_gaps.py gives:
 
```
...
he: computing Gamma...
Traceback (most recent call last):
  File "./simple.py", line 190, in <module>
    main()
  File "./simple.py", line 187, in main
    app()
  File "/home/vlukes/work/prog/sfepy/sfepy/applications/application.py", line 29, in call_basic
    return self.call(**kwargs)
  File "/home/vlukes/work/prog/sfepy/sfepy/homogenization/homogen_app.py", line 240, in call
    aux = self.he(ret_all=ret_all, time_tag=time_tag)
  File "/home/vlukes/work/prog/sfepy/sfepy/applications/application.py", line 29, in call_basic
    return self.call(**kwargs)
  File "/home/vlukes/work/prog/sfepy/sfepy/homogenization/engine.py", line 735, in call
    worker(problem, opts, self.post_process_hook,
  File "/home/vlukes/work/prog/sfepy/sfepy/homogenization/engine.py", line 101, in __call__
    val = self.calculate_req(problem, options, post_process_hook,
  File "/home/vlukes/work/prog/sfepy/sfepy/homogenization/engine.py", line 257, in calculate_req
    val = HomogenizationWorker.calculate(mini_app, problem,
  File "/home/vlukes/work/prog/sfepy/sfepy/homogenization/engine.py", line 143, in calculate
    val = mini_app(volume, data=data)
  File "/home/vlukes/work/prog/sfepy/sfepy/homogenization/coefs_phononic.py", line 1149, in __call__
    assert_(dim == iw_dir.shape[0])
IndexError: tuple index out of range
```

**Comment by rc** [comment]
Those examples need to be run suing the `phonon.py` script.

**Comment by vlukes** [comment]
Right :)
