### ISSUE TITLE
"IndexError: Index 184758 is out of bounds for axis 0 with size 184758" encountered when using Problem.solve ()

### ISSUE THREAD

**Issue by wuhaozede** [sfepy/sfepy#848]
I'm going to use the Sfepy library to handle the linear elasticity problem for my kidneys.

After I've loaded the kidney, pelvis, and cyst using FEDomain(), and defined the Material parameters using Material(). When I call sfepy. Discrete '. Problem. Solve() when I met a fatal mistake.

`Traceback (most recent call last):
  File "f:\vscode\Python\\main.py", line 308, in <module>
    variables = pb.solve(status=status)
  File "D:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\sfepy-2022.2-py3.7-win-amd64.egg\sfepy\discrete\problem.py", line 1416, in solve
    self.time_update(tss.ts)
  File "D:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\sfepy-2022.2-py3.7-win-amd64.egg\sfepy\discrete\problem.py", line 692, in time_update
    functions, create_matrix, is_matrix)
  File "D:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\sfepy-2022.2-py3.7-win-amd64.egg\sfepy\discret    verbose=self.conf.get('verbose', True))
  File "D:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\sfepy-2022.2-py3.7-win-amd64.egg\sfepy\discrete\equations.py", line 307, in time_update
    active_only=active_only)
  File "D:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\sfepy-2022.2-py3.7-win-amd64.egg\sfepy\discrete\variables.py", line 430, in equation_mapping
    problem=problem)
  File "D:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\sfepy-2022.2-py3.7-win-amd64.egg\sfepy\discrete\variables.py", line 1560, in equation_mapping
    problem=problem, warn=warn)
  File "D:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\sfepy-2022.2-py3.7-win-amd64.egg\sfepy\discrete\common\dof_info.py", line 386, in map_equations
    master_nod_list = field.get_dofs_in_region(region)
  File "D:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\sfepy-2022.2-py3.7-win-amd64.egg\sfepy\discrete\fem\fields_base.py", line 498, in get_dofs_in_region
    self.edge_dofs)
  File "D:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\sfepy-2022.2-py3.7-win-amd64.egg\sfepy\discrete\fem\fields_base.py", line 409, in _get_facet_dofs
    facets = remap[rfacets]
IndexError: index 184758 is out of bounds for axis 0 with size 184758`

I checked the input input.mesh file and opened the input.mesh using the official resview.py, but did not find any exception.

Facing this mistake, I don't have a good way to solve the problem. I would like to ask the maintenance personnel, what should I do?

**Comment by vlukes** [comment]
Hi @wuhaozede,

I assume some problem in the mesh, eg. discontinuous numbering of nodes or cells. Could you provide a minimal working code and the mesh file?

**Comment by wuhaozede** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by vlukes** [comment]
Hi @wuhaozede,

In your code, the equations are defined in `domain` and the boundary conditions in `domain1` and `domain2`. This can not work! You must use just one `FEDomain`. I suggest to merge the mesh parts into one mesh file, label the parts by different material ids, and define  the regions as follows:

```
mesh = Mesh.from_file('all_parts_together.mesh')
domain = FEDomain('domain', mesh)
omega = domain.create_region('Omega', 'cells of group 1')
omega1 = domain.create_region('Omega1', 'cells of group 2')
omega2 = domain.create_region('Omega2', 'cells of group 3')
```

Regards
Vladimir

**Comment by wuhaozede** [comment]
Thank you very much for your advice. I will try to solve this problem right away！
