### ISSUE TITLE
Trouble installing SfePy on Python 3.10.7

### ISSUE THREAD

**Issue by SebfraOslo** [sfepy/sfepy#879]
Hi,  

I am trying to install SfePy on Python 3.10.7 (with pip) but it doesn't work. It gives me the message error:
" ERROR: Failed building wheel for sfepy
Failed to build sfepy
ERROR: Could not build wheels for sfepy, which is required to install pyproject.toml-based projects"

Thank you
Sebastien

**Comment by rc** [comment]
Hi Sebastien,

Thanks for the report.  The pip install is a new feature, so rough edges are to be expected. Could you run pip with `-v` option and paste the whole output here? What is your platform?

**Comment by SebfraOslo** [comment]
Hi Robert,

Thanks for your reply. 
My Platform is a PC (Windows 10). When I type pip -v, it gives:
"Usage:
  C:\Users\sebas\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe -m pip <command> [options]

Commands:
  install                     Install packages.
  download                    Download packages.
  uninstall                   Uninstall packages.
  freeze                      Output installed packages in requirements format.
  inspect                     Inspect the python environment.
  list                        List installed packages.
  show                        Show information about installed packages.
  check                       Verify installed packages have compatible dependencies.
  config                      Manage local and global configuration.
  search                      Search PyPI for packages.
  cache                       Inspect and manage pip's wheel cache.
  index                       Inspect information available from package indexes.
  wheel                       Build wheels from your requirements.
  hash                        Compute hashes of package archives.
  completion                  A helper command used for command completion.
  debug                       Show information useful for debugging.
  help                        Show help for commands.

General Options:
  -h, --help                  Show help.
  --debug                     Let unhandled exceptions propagate outside the main subroutine, instead of logging them to       
                              stderr.
  --isolated                  Run pip in an isolated mode, ignoring environment variables and user configuration.
  --require-virtualenv        Allow pip to only run in a virtual environment; exit with an error otherwise.
  -v, --verbose               Give more output. Option is additive, and can be used up to 3 times.
  -V, --version               Show version and exit.
  -q, --quiet                 Give less output. Option is additive, and can be used up to 3 times (corresponding to WARNING,   
                              ERROR, and CRITICAL logging levels).
  --log <path>                Path to a verbose appending log.
  --no-input                  Disable prompting for input.
  --proxy <proxy>             Specify a proxy in the form scheme://[user:passwd@]proxy.server:port.
  --retries <retries>         Maximum number of retries each connection should attempt (default 5 times).
  --timeout <sec>             Set the socket timeout (default 15 seconds).
  --exists-action <action>    Default action when a path already exists: (s)witch, (i)gnore, (w)ipe, (b)ackup, (a)bort.        
  --trusted-host <hostname>   Mark this host or host:port pair as trusted, even though it does not have valid or any HTTPS.    
  --cert <path>               Path to PEM-encoded CA certificate bundle. If provided, overrides the default. See 'SSL
                              Certificate Verification' in pip documentation for more information.
  --client-cert <path>        Path to SSL client certificate, a single file containing the private key and the certificate in  
                              PEM format.
  --cache-dir <dir>           Store the cache data in <dir>.
  --no-cache-dir              Disable the cache.
  --disable-pip-version-check
                              Don't periodically check PyPI to determine whether a new version of pip is available for
                              download. Implied with --no-index.
  --no-color                  Suppress colored output.
  --no-python-version-warning
                              Silence deprecation warnings for upcoming unsupported Pythons.
  --use-feature <feature>     Enable new functionality, that may be backward incompatible.
  --use-deprecated <feature>  Enable deprecated functionality, that will be removed in the future."

Sebastien

**Comment by SebfraOslo** [comment]
Hi again Robert,

I have managed to install SfePy through Anaconda. Now, when I try to run a code with sfepy-run it gives a message error. For example, when I type "sfepy-run poisson_short_syntax.py" it says:
"usage: sfepy-run-script.py [command] [options]
sfepy-run-script.py: error: argument command: invalid choice: 'cube.py' (choose from 'extractor', 'probe', 'resview', 'simple')"

Thank you
Sebastien

**Comment by rc** [comment]
It seems that you have an older version than 2022.3 in Anaconda, is that so? If yes, try upgrading to 2022.3.
Otherwise, can you find which sfepy-run script is actually run (try `where sfepy-run`) - I suspect there might be some old files lying around?

As for pip, I meant `pip -vvv install sfepy` :) I would like to see what lead to your error.

**Comment by SebfraOslo** [comment]
Indeed, my version is 2022.2. I have installed it through conda-forge. But I don't see how I can install 2022.3 from Conda?

Otherwise I have tried "pip -vvv install sfepy" and sfepy 2022.2 installs succesfully. 

Sebastien

**Comment by SebfraOslo** [comment]
I have tried to upgrade 2022.2 to 2022.3 using " conda upgrade -c conda-forge sfepy" but it does not work. There is no error message but my installed version is 2022.2.

Sebastien

**Comment by rc** [comment]
Strange - have a look at https://anaconda.org/conda-forge/sfepy/files - there is the version 2022.3 also for win-64. BTW. try not mixing pip and conda - did you try pip outside the conda environment?

**Comment by SebfraOslo** [comment]
Yes, indeed I tried "pip -vvv" in the conda environment. Afterwards I tried "pip -vvv" outside conda but it did not work

**Comment by rc** [comment]
Can you send the output of the pip command outside conda?

**Comment by SebfraOslo** [comment]
This is the message I got when I type "pip -vvv install sfepy". The message is much too long so I only show the last part:
"Generating code
  Finished generating code
  LINK : fatal error LNK1158: cannot run 'rc.exe'
  error: Command "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.33.31629\bin\HostX86\x64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2032.0_x64__qbz5n2kfra8p0\libs /LIBPATH:C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2032.0_x64__qbz5n2kfra8p0 /LIBPATH:C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2032.0_x64__qbz5n2kfra8p0\PCbuild\amd64 /LIBPATH:build\temp.win-amd64-3.10 /LIBPATH:C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.33.31629\ATLMFC\lib\x64 /LIBPATH:C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.33.31629\lib\x64 /LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\ucrt\x64 /LIBPATH:C:\Program Files (x86)\Windows Kits\10\\lib\10.0.19041.0\\um\x64 sfepy_common.lib /EXPORT:PyInit__fmfield build\temp.win-amd64-3.10\Release\build\src.win-amd64-3.10\sfepy\discrete\common\extmods\_fmfield.obj /OUT:build\lib.win-amd64-3.10\sfepy\discrete\common\extmods\_fmfield.cp310-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.10\Release\build\src.win-amd64-3.10\sfepy\discrete\common\extmods\_fmfield.cp310-win_amd64.lib" failed with exit status 1158

  ########### EXT COMPILER OPTIMIZATION ###########
  Platform      :
    Architecture: x64
    Compiler    : msvc

  CPU baseline  :
    Requested   : 'min'
    Enabled     : SSE SSE2 SSE3
    Flags       : none
    Extra checks: none

  CPU dispatch  :
    Requested   : 'max -xop -fma4'
    Enabled     : SSSE3 SSE41 POPCNT SSE42 AVX F16C FMA3 AVX2 AVX512F AVX512CD AVX512_SKX AVX512_CLX AVX512_CNL AVX512_ICL
    Generated   : none
  CCompilerOpt.cache_flush[809] : write cache to path -> C:\Users\sebas\AppData\Local\Temp\pip-install-lm8pmh2f\sfepy_8e4eb49b534f4d44889727c06f60c4a9\build\temp.win-amd64-3.10\Release\ccompiler_opt_cache_ext.py

  ########### CLIB COMPILER OPTIMIZATION ###########
  Platform      :
    Architecture: x64
    Compiler    : msvc

  CPU baseline  :
    Requested   : 'min'
    Enabled     : SSE SSE2 SSE3
    Flags       : none
    Extra checks: none

  CPU dispatch  :
    Requested   : 'max -xop -fma4'
    Enabled     : SSSE3 SSE41 POPCNT SSE42 AVX F16C FMA3 AVX2 AVX512F AVX512CD AVX512_SKX AVX512_CLX AVX512_CNL AVX512_ICL
    Generated   : none
  CCompilerOpt.cache_flush[809] : write cache to path -> C:\Users\sebas\AppData\Local\Temp\pip-install-lm8pmh2f\sfepy_8e4eb49b534f4d44889727c06f60c4a9\build\temp.win-amd64-3.10\ccompiler_opt_cache_clib.py
  error: subprocess-exited-with-error
  
  × Building wheel for sfepy (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: 'C:\Users\sebas\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe' 'C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2032.0_x64__qbz5n2kfra8p0\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' build_wheel 'C:\Users\sebas\AppData\Local\Temp\tmpb7t5reb0'
  cwd: C:\Users\sebas\AppData\Local\Temp\pip-install-lm8pmh2f\sfepy_8e4eb49b534f4d44889727c06f60c4a9
  Building wheel for sfepy (pyproject.toml) ... error
  ERROR: Failed building wheel for sfepy
Failed to build sfepy
ERROR: Could not build wheels for sfepy, which is required to install pyproject.toml-based projects
Exception information:
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2032.0_x64__qbz5n2kfra8p0\lib\site-packages\pip\_internal\cli\base_command.py", line 167, in exc_logging_wrapper
    status = run_func(*args)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2032.0_x64__qbz5n2kfra8p0\lib\site-packages\pip\_internal\cli\req_command.py", line 247, in wrapper
    return func(self, options, args)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2032.0_x64__qbz5n2kfra8p0\lib\site-packages\pip\_internal\commands\install.py", line 431, in run
    raise InstallationError(
pip._internal.exceptions.InstallationError: Could not build wheels for sfepy, which is required to install pyproject.toml-based projects
Remote version of pip: 22.2.2
Local version of pip:  22.2.2
Was pip installed by pip? True
Removed build tracker: 'C:\\Users\\sebas\\AppData\\Local\\Temp\\pip-build-tracker-ps1smsb0'"

**Comment by SebfraOslo** [comment]
I am trying to install 2022.3 using "conda install -c conda-forge sfepy=2022.3" (on Win 64) but it takes forever. It is examning conflicts

Sebastien

**Comment by rc** [comment]
Maybe try a fresh miniconda install? I have just tried it and it worked OK.

**Comment by SebfraOslo** [comment]
Hi, 
I could successfully install 2022.3 from miniconda. However, this time when I type "sfepy-run poisson_short_syntax.py" it gives a new message error:
"Fatal error in launcher: Unable to create process using '"D:\bld\sfepy_1664559573405\_h_env\python.exe"  "C:\Users\sebas\miniconda3\Scripts\sfepy-run.exe" poisson_short_syntax.py': The system cannot find the file specified."

Sebastien

**Comment by rc** [comment]
Can you run just `sfepy-run` without arguments?

**Comment by SebfraOslo** [comment]
When I just run "sfepy-run" it gives the error message:
"Fatal error in launcher: Unable to create process using '"D:\bld\sfepy_1664559573405\_h_env\python.exe"  "C:\Users\sebas\miniconda3\Scripts\sfepy-run.exe" ': The system cannot find the file specified."

**Comment by rc** [comment]
I am trying to fix the sfepy-feedstock package for conda in https://github.com/conda-forge/sfepy-feedstock/pull/47, for the moment, you can install the dependencies using conda, and try building sfepy from sources(?)

**Comment by rc** [comment]
Did the conda package update help? It helped on a windows box I have tried.

**Comment by flothesof** [comment]
I have found a workaround to the problems reported by @SebfraOslo (I have exactly the same symptoms).

To install from source I had to:
- install from conda-forge as a way to install all dependencies at once
- comment out the line `package_check('meshio', INFO.MESHIO_MIN_VERSION, show_only=show_only)` in `setup.py`
- build the Cython extension in-place `python setup.py build_ext --inplace`
- use `pip install -e .`

If I don’t do the above I get multiple errors:
- a *wrongly* not passing meshio check, possibly related to #885 
- the compilation error linked in this thread involving rc.exe not working correctly

Hope this helps.

Florian

**Comment by rc** [comment]
Hi Florian,

thanks for the workaround! 

FWIW, I am aware that the checks in setup.py should not prevent building the extension modules. But I do not want to invest too much effort into fixing that, due to numpy.distutils (which we use) [being deprecated](https://numpy.org/doc/stable/reference/distutils_status_migration.html#status-of-numpy-distutils-and-migration-advice). SciPy and NumPy are switching to Meson. We should probably do the same, but it will not be trivial.

So for the moment, disabling the meshio check might be the best solution.

**Comment by yosefm** [comment]
@flothesof - the meshio issue seems to be (at least for Python 3.9) related to a clash between the sfepy build dep on `oldest-numpy-version` (1.19.3 for py 3.9) vs meshio's need for `numpy>=1.20`. That later requirement is specified in their pyproject.toml but not their setup.cfg, which appears to take precedence. Fixing it on meshio's side won't help, as it'll just create a straight-up dependency clash. Ok, maybe it would at least make the issue more obvious, but won't solve it.

My suggestion: replace sfepy's dependency to numpy>=1.20 at least for python 3.9. How does that sound?
