### ISSUE TITLE
Wheel installation error

### ISSUE THREAD

**Issue by gakabani** [sfepy/sfepy#885]
I am getting a sfepy installation error. I am using Python 3.9.11 on a mac OS 12.6.
The error is described below. I am no expert on python, so I claim innocence. 
Any help will be appreciated.

Thanks
____________________________
Collecting sfepy
  Using cached sfepy-2022.3.tar.gz (16.1 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [29 lines of output]
      sympy (optional) is missing; some tests are going to fail!
      igakit (optional) is missing; you may get run-time errors
      petsc4py (optional) is missing; you may get run-time errors
      mpi4py (optional) is missing; you may get run-time errors
      slepc4py (optional) is missing; you may get run-time errors
      pymetis (optional) is missing; you may get run-time errors
      scikits.umfpack (optional) is missing; you may get run-time errors
      Traceback (most recent call last):
        File "/Users/gamalakabani/.pyenv/versions/3.9.11/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module>
          main()
        File "/Users/gamalakabani/.pyenv/versions/3.9.11/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 333, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/gamalakabani/.pyenv/versions/3.9.11/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/private/var/folders/lc/tbblv6l95sz47jzgk5nkbjyc0000gn/T/pip-build-env-pii6692x/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 162, in get_requires_for_build_wheel
          return self._get_build_requires(
        File "/private/var/folders/lc/tbblv6l95sz47jzgk5nkbjyc0000gn/T/pip-build-env-pii6692x/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 143, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/lc/tbblv6l95sz47jzgk5nkbjyc0000gn/T/pip-build-env-pii6692x/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 267, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/private/var/folders/lc/tbblv6l95sz47jzgk5nkbjyc0000gn/T/pip-build-env-pii6692x/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 158, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 214, in <module>
          check_versions()
        File "setup.py", line 127, in check_versions
          package_check('meshio', INFO.MESHIO_MIN_VERSION,
        File "/private/var/folders/lc/tbblv6l95sz47jzgk5nkbjyc0000gn/T/pip-install-duq1is43/sfepy_f1d314b22715441b9d9ec2be2cc11e06/./tools/build_helpers.py", line 314, in package_check
          raise RuntimeError(msgs['missing'] % pkg_name)
      RuntimeError: meshio is missing
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by vlukes** [comment]
Hi @gakabani,

the [meshio](https://github.com/nschloe/meshio) library seems to be missing. Try to install it manually and then run the _Sfepy_ installation again.

Regards
Vladimir

**Comment by rc** [comment]
FWIW:  there is still the constraint 4.4.6 that we need `meshio==4.4.6`.

**Comment by artizzq** [comment]
I guess you can use Anaconda environment
