### ISSUE TITLE
 Can't install Sfepy inside PyCharm virtualenv and using cmd on Windows 11

### ISSUE THREAD

**Issue by artizzq** [sfepy/sfepy#889]
Hello, I cant install Sfepy
```
**PS C:\Users\Windground\PycharmProjects\coreReconstruction> pip install meshio[all]** 
Requirement already satisfied: meshio[all] in c:\users\windground\pycharmprojects\nnet1\venv\lib\site-packages (5.3.4)
Requirement already satisfied: numpy in c:\users\windground\pycharmprojects\nnet1\venv\lib\site-packages (from meshio[all]) (1.21.5)
Requirement already satisfied: rich in c:\users\windground\pycharmprojects\nnet1\venv\lib\site-packages (from meshio[all]) (12.5.1)
Collecting netCDF4
  Downloading netCDF4-1.6.1-cp39-cp39-win_amd64.whl (5.2 MB)
     |████████████████████████████████| 5.2 MB 211 kB/s
Requirement already satisfied: h5py in c:\users\windground\pycharmprojects\nnet1\venv\lib\site-packages (from meshio[all]) (3.6.0)
Collecting cftime
  Downloading cftime-1.6.2-cp39-cp39-win_amd64.whl (171 kB)
     |████████████████████████████████| 171 kB 504 kB/s
Requirement already satisfied: pygments<3.0.0,>=2.6.0 in c:\users\windground\pycharmprojects\nnet1\venv\lib\site-packages (from rich->meshio[all]) (2.11.2)
Requirement already satisfied: commonmark<0.10.0,>=0.9.0 in c:\users\windground\pycharmprojects\nnet1\venv\lib\site-packages (from rich->meshio[all]) (0.9.1)
Installing collected packages: cftime, netCDF4
Successfully installed cftime-1.6.2 netCDF4-1.6.1
WARNING: You are using pip version 21.1.2; however, version 22.3 is available.
You should consider upgrading via the 'C:\Users\Windground\PycharmProjects\nnet1\venv\Scripts\python.exe -m pip install --upgrade pip' command.
**PS C:\Users\Windground\PycharmProjects\coreReconstruction> pip install sfepy**      
Collecting sfepy
  Using cached sfepy-2022.3.tar.gz (16.1 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\Windground\PycharmProjects\nnet1\venv\Scripts\python.exe' 'C:\Users\Windground\PycharmProjects\nnet1\venv\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' get_requires_for_build_wheel 'C:\Users\WINDGR~1\AppData\Local\Temp\tmpoci2dxr2'
       cwd: C:\Users\Windground\AppData\Local\Temp\pip-install-c_zgvc0x\sfepy_36ce7d5c7de34639a104c280b65a676e
  Complete output (29 lines):
  sympy (optional) is missing; some tests are going to fail!
  igakit (optional) is missing; you may get run-time errors
  petsc4py (optional) is missing; you may get run-time errors
  mpi4py (optional) is missing; you may get run-time errors
  slepc4py (optional) is missing; you may get run-time errors
  pymetis (optional) is missing; you may get run-time errors
  scikits.umfpack (optional) is missing; you may get run-time errors
  Traceback (most recent call last):
    File "C:\Users\Windground\PycharmProjects\nnet1\venv\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 280, in <module>
      main()
    File "C:\Users\Windground\PycharmProjects\nnet1\venv\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "C:\Users\Windground\PycharmProjects\nnet1\venv\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 114, in get_requires_for_build_wheel
      return hook(config_settings)
    File "C:\Users\Windground\AppData\Local\Temp\pip-build-env-5fjzkf8f\overlay\Lib\site-packages\setuptools\build_meta.py", line 162, in get_requires_for_build_wheel
      return self._get_build_requires(
    File "C:\Users\Windground\AppData\Local\Temp\pip-build-env-5fjzkf8f\overlay\Lib\site-packages\setuptools\build_meta.py", line 143, in _get_build_requires
      self.run_setup()
    File "C:\Users\Windground\AppData\Local\Temp\pip-build-env-5fjzkf8f\overlay\Lib\site-packages\setuptools\build_meta.py", line 267, in run_setup
      super(_BuildMetaLegacyBackend,
    File "C:\Users\Windground\AppData\Local\Temp\pip-build-env-5fjzkf8f\overlay\Lib\site-packages\setuptools\build_meta.py", line 158, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 214, in <module>
      check_versions()
    File "setup.py", line 127, in check_versions
      package_check('meshio', INFO.MESHIO_MIN_VERSION,
    File "./tools\build_helpers.py", line 314, in package_check
      raise RuntimeError(msgs['missing'] % pkg_name)
  RuntimeError: meshio is missing
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/3c/fc/e8022fdeed181454f86ae100f8608efaab309f9f22471fd15ea04c312e25/sfepy-2022.3.tar.gz#sha256=16bbc941c494e3ffe00cd0c3a9a277b6ff22a1aa9c19d826456d74ce1f7f22db (from https:/
/pypi.org/simple/sfepy/). Command errored out with exit status 1: 'C:\Users\Windground\PycharmProjects\nnet1\venv\Scripts\python.exe' 'C:\Users\Windground\PycharmProjects\nnet1\venv\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' get_requires_for_build_wheel 'C:\Users\WINDGR~1\AppData\Local\Temp\tmpoci2dxr2' Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement sfepy (from versions: 2022.3a1, 2022.3)
ERROR: No matching distribution found for sfepy
WARNING: You are using pip version 21.1.2; however, version 22.3 is available.
You should consider upgrading via the 'C:\Users\Windground\PycharmProjects\nnet1\venv\Scripts\python.exe -m pip install --upgrade pip' command.
```
I dont have an idea why it doesnt recognize meshio inside PyCharm.
I also experience this outside of PyCharm using cmd in Windows

**Comment by artizzq** [comment]
Solved using Conda environment inside PyCharm

**Comment by rc** [comment]
Hey @artizzq, a colleague of mine has a similar problem on WIndows - he needs to use the git version of sfepy within miniconda, and got the same error (missing meshio, although it is installed) - can you share your solution? Thanks!

**Comment by artizzq** [comment]
Hello! Yeah, sure.

`conda install -c conda-forge pyvista
conda install -c conda-forge meshio
conda install -c conda-forge sfepy`

**Comment by rc** [comment]
Thanks! I wonder what causes the "missing meshio" error.
