### ISSUE TITLE
mem_free_mem(): error exit!

### ISSUE THREAD

**Issue by artizzq** [sfepy/sfepy#890]
Could you please guide me whats going on in this output and why I cant process mesh.
For example I used my own created mesh and I got this thing:
```
PS C:\Users\Windground\PycharmProjects\sfepy_test> python test.py                     
sfepy: using values:
sfepy:   diffusivity: 1e-05
sfepy:   max. IC value: 2.0
sfepy: reading mesh (test1.mesh)...
sfepy:   number of vertices: 148032
sfepy:   number of cells:
sfepy:     2_3: 430595
sfepy: ...done in 1.34 s
sfepy: warning: mesh with topological dimension 2 lower than space dimension 3
sfepy: - element orientation not checked!
sfepy: updating variables...
sfepy: ...done
sfepy: setting up dof connectivities...
sfepy: ...done in 0.01 s
sfepy: matrix shape: (478, 478)
sfepy: assembling matrix graph...
sfepy: ...done in 0.01 s
sfepy: matrix structural nonzeros: 1234 (5.40e-01% fill)
sfepy: updating materials...
sfepy:     m
sfepy: ...done in 0.16 s
mem_free_mem(): error exit!
mem_free_mem(): error exit!
mem_free_mem(): error exit!
mem_free_mem(): error exit!
mem_free_mem(): error exit!
mem_free_mem(): error exit!
sfepy: matrix evaluation failed, giving up...
Traceback (most recent call last):
  File "test.py", line 104, in <module>
    main()
  File "test.py", line 101, in main
    pb.solve()
  File "C:\ProgramData\Anaconda3\envs\sfepy_test\lib\site-packages\sfepy\discrete\problem.py", line 1442, in solve
    mtx = prepare_matrix(self, variables) # Updates materials.
  File "C:\ProgramData\Anaconda3\envs\sfepy_test\lib\site-packages\sfepy\discrete\problem.py", line 84, in prepare_matrix
    mtx = ev.eval_tangent_matrix(state(), is_full=True)
  File "C:\ProgramData\Anaconda3\envs\sfepy_test\lib\site-packages\sfepy\discrete\evaluate.py", line 98, in eval_tangent_matrix
    mtx = pb.equations.eval_tangent_matrices(vec, mtx)
  File "C:\ProgramData\Anaconda3\envs\sfepy_test\lib\site-packages\sfepy\discrete\equations.py", line 732, in eval_tangent_matrices
    asm_obj=tangent_matrix)
  File "C:\ProgramData\Anaconda3\envs\sfepy_test\lib\site-packages\sfepy\discrete\equations.py", line 607, in evaluate
    term_mode=term_mode, asm_obj=asm_obj)
  File "C:\ProgramData\Anaconda3\envs\sfepy_test\lib\site-packages\sfepy\discrete\equations.py", line 848, in evaluate
    ret_status=True)
  File "C:\ProgramData\Anaconda3\envs\sfepy_test\lib\site-packages\sfepy\terms\terms.py", line 1477, in evaluate
    fargs = self.call_get_fargs(_args, kwargs)
  File "C:\ProgramData\Anaconda3\envs\sfepy_test\lib\site-packages\sfepy\terms\terms.py", line 1314, in call_get_fargs
    fargs = self.get_fargs(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\sfepy_test\lib\site-packages\sfepy\terms\terms_dot.py", line 96, in get_fargs
    vgeo, _ = self.get_mapping(virtual)
  File "C:\ProgramData\Anaconda3\envs\sfepy_test\lib\site-packages\sfepy\terms\terms.py", line 1093, in get_mapping
    return_key=return_key)
  File "C:\ProgramData\Anaconda3\envs\sfepy_test\lib\site-packages\sfepy\discrete\common\fields.py", line 247, in get_mapping
    out = self.create_mapping(region, integral, integration)
  File "C:\ProgramData\Anaconda3\envs\sfepy_test\lib\site-packages\sfepy\discrete\fem\fields_base.py", line 1020, in create_mapping
    ori=self.ori, transform=transform)
  File "C:\ProgramData\Anaconda3\envs\sfepy_test\lib\site-packages\sfepy\discrete\fem\mappings.py", line 105, in get_mapping
    cmap.describe(self.coors, self.conn, bf_g, ebf_g, weights)
  File "sfepy\discrete\common\extmods\mappings.pyx", line 104, in sfepy.discrete.common.extmods.mappings.CMapping.describe
ValueError: ccore error (see above)
```

Source code (used code from https://zenodo.org/record/1434071):
```
#!/usr/bin/env python
"""
Transient 3D heat conduction (Laplace equation) with non-constant initial
conditions given by a function. Uses the imperative API of SfePy.

Run this example using::

  python heat_cond_interactive.py -h
  python heat_cond_interactive.py

Show the results using the Mayavi-based GUI::

  python postproc.py cylinder.??.vtk -b
"""
from argparse import ArgumentParser, RawDescriptionHelpFormatter
import os
import numpy as np

from sfepy.base.base import output, IndexedStruct
from sfepy.discrete import (FieldVariable, Material, Integral, Function,
                            Equation, Equations, Problem)
from sfepy.discrete.fem import Mesh, FEDomain, Field
from sfepy.terms import Term
from sfepy.discrete.conditions import Conditions, EssentialBC, InitialCondition
from sfepy.solvers.ls import ScipyDirect
from sfepy.solvers.nls import Newton
from sfepy.solvers.ts_solvers import SimpleTimeSteppingSolver
import numpy as np

helps = {
    'diffusivity' : 'the diffusivity coefficient [default: %(default)s]',
    'ic_max' : 'the max. initial condition value [default: %(default)s]',
}

def main():
    from sfepy import data_dir

    parser = ArgumentParser(description=__doc__,
                            formatter_class=RawDescriptionHelpFormatter)
    parser.add_argument('--version', action='version', version='%(prog)s')
    parser.add_argument('--diffusivity', metavar='float', type=float,
                        action='store', dest='diffusivity',
                        default=1e-5, help=helps['diffusivity'])
    parser.add_argument('--ic-max', metavar='float', type=float,
                        action='store', dest='ic_max',
                        default=2.0, help=helps['ic_max'])
    options = parser.parse_args()

    output('using values:')
    output('  diffusivity:', options.diffusivity)
    output('  max. IC value:', options.ic_max)

    mesh = Mesh.from_file('test1.mesh')
    domain = FEDomain('cylinder', mesh)

    m = Material('m', c=options.diffusivity)

    omega = domain.create_region('Omega', 'all')
    left = domain.create_region('Left',
                                'vertices in x < 0.00001',
                                'facet')
    right = domain.create_region('Right',
                                 'vertices in x > 0.099999',
                                 'facet')

    field = Field.from_args('temperature', np.float64, 'scalar',
                            omega, approx_order=1)

    u = FieldVariable('u', 'unknown', field, history=1)
    v = FieldVariable('v', 'test', field, primary_var_name='u')

    ebc1 = EssentialBC('u1', left, {'u.0' : 2.0})
    ebc2 = EssentialBC('u2', right, {'u.0' : -2.0})

    def get_ic(coors, ic):
        x, y, z = coors.T
        return 2 - 40.0 * x + options.ic_max * np.sin(4 * np.pi * x / 0.1)
    ic_fun = Function('ic_fun', get_ic)
    ic = InitialCondition('ic', omega, {'u.0' : ic_fun})

    integral = Integral('i', order=2)

    t1 = Term.new('dw_volume_dot(v, du/dt)',
                  integral, omega, v=v, u=u)
    t2 = Term.new('dw_laplace(m.c, v, u)',
                  integral, omega, m=m, v=v, u=u)
    eq = Equation('balance', t1 + t2)
    eqs = Equations([eq])

    pb = Problem('heat', equations=eqs)
    pb.set_bcs(ebcs=Conditions([ebc1, ebc2]))
    pb.set_ics(Conditions([ic]))

    ls = ScipyDirect({})
    nls_status = IndexedStruct()
    nls = Newton({'is_linear' : True}, lin_solver=ls, status=nls_status)
    tss = SimpleTimeSteppingSolver({'t0' : 0.0, 't1' : 100.0, 'n_step' : 11},
                                   nls=nls, context=pb, verbose=True)
    pb.set_solver(tss)

    pb.solve()

if __name__ == '__main__':
    main()
```

Mesh info:
```
PS C:\Users\Windground\PycharmProjects\sfepy_test> python show_mesh_info.py test1.mesh
sfepy: reading mesh (test1.mesh)...
sfepy:   number of vertices: 148032
sfepy:   number of cells:
sfepy:     2_3: 430595
sfepy: ...done in 1.34 s
sfepy: CMesh: n_coor: 148032, dim 3, tdim: 2, n_el 430595
sfepy: element types: ['2_3']
sfepy: nodal BCs: []
sfepy: bounding box:
x: [ 0.0000000e+00,  1.4900000e+02]
y: [ 4.0000000e+00,  2.5500000e+02]
z: [ 4.0000000e+00,  2.5500000e+02]
sfepy: centre:           [ 7.4500000e+01,  1.2950000e+02,  1.2950000e+02]
sfepy: coordinates mean: [ 7.4370529e+01,  1.3394157e+02,  1.3094031e+02]
```
My mesh represents porous medium (capture from GMSH):
![image](https://user-images.githubusercontent.com/56273839/200159240-8dc610dd-2af0-4a7e-bf83-fa4bad2a8ee8.png)
It has size about 21 megabyte.
Mesh properties from GMSH:
![image](https://user-images.githubusercontent.com/56273839/200159320-c2ff6748-b364-4330-aad4-4a7af3af9909.png)
![image](https://user-images.githubusercontent.com/56273839/200159294-fe1d578e-ba8a-4e0f-a277-9486f79c6e71.png)

**Comment by artizzq** [comment]
Feels like it's something with the mesh so I found another workaround

**Comment by rc** [comment]
FWIW the problem was that you used a surface (2D) mesh embedded in 3D.
