### ISSUE TITLE
Not enough memory to perform factorization.

### ISSUE THREAD

**Issue by artizzq** [sfepy/sfepy#894]
```
sfepy: using values:
sfepy:   diffusivity: 1e-05
sfepy:   max. IC value: 2.0
sfepy: updating variables...
sfepy: ...done
sfepy: setting up dof connectivities...
sfepy: ...done in 0.44 s
sfepy: matrix shape: (8195468, 8195468)
sfepy: assembling matrix graph...
sfepy: ...done in 7.88 s
sfepy: matrix structural nonzeros: 174411432 (2.60e-04% fill)
sfepy: updating materials...
sfepy:     m
sfepy: ...done in 8.20 s
sfepy: presolve: 5.47 [s]
sfepy: ====== time 0.000000e+00 (step  1 of 11) =====
sfepy: updating variables...
sfepy: ...done
sfepy: updating materials...
sfepy:     m
sfepy: ...done in 0.00 s
sfepy: initial residual: 1.158259e-01
sfepy: ====== time 1.000000e+01 (step  2 of 11) =====
sfepy: updating variables...
sfepy: ...done
sfepy: updating materials...
sfepy:     m
sfepy: ...done in 0.00 s
sfepy: nls: iter: 0, residual: 1.158259e-01 (rel: 1.000000e+00)
Not enough memory to perform factorization.

Process finished with exit code -1073741819 (0xC0000005)
```
I've just tried to modify the code in ...\Lib\site-packages\sfepy\solvers\ls.py
And I wrote the following:
```
        if is_new or (self.solve is None):
            from pypardiso import factorized
            self.solve = factorized(mtx.astype('int64'))
            self.mtx_digest = mtx_digest
```
You wanna know why I modified it? Because previous code resulted in the following:
```
sfepy: using values:
sfepy:   diffusivity: 1e-05
sfepy:   max. IC value: 2.0
sfepy: updating variables...
sfepy: ...done
sfepy: setting up dof connectivities...
sfepy: ...done in 0.36 s
sfepy: matrix shape: (8195468, 8195468)
sfepy: assembling matrix graph...
sfepy: ...done in 5.07 s
sfepy: matrix structural nonzeros: 174411432 (2.60e-04% fill)
sfepy: updating materials...
sfepy:     m
sfepy: ...done in 5.41 s
Not enough memory to perform factorization.
Traceback (most recent call last):
  File "C:/Users/Windground/PycharmProjects/sfepy_test/test.py", line 906, in <module>
    main()
  File "C:/Users/Windground/PycharmProjects/sfepy_test/test.py", line 903, in main
    variables = pb.solve(status=status)
  File "C:\ProgramData\Anaconda3\envs\sfepy_test\lib\site-packages\sfepy\discrete\problem.py", line 1443, in solve
    self.try_presolve(mtx)
  File "C:\ProgramData\Anaconda3\envs\sfepy_test\lib\site-packages\sfepy\discrete\problem.py", line 1204, in try_presolve
    ls.presolve(mtx)
  File "C:\ProgramData\Anaconda3\envs\sfepy_test\lib\site-packages\sfepy\solvers\ls.py", line 219, in presolve
    self.solve = self.sls.splu(mtx)
  File "C:\ProgramData\Anaconda3\envs\sfepy_test\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py", line 339, in splu
    ilu=False, options=_options)
SystemError: gstrf was called with invalid arguments

Process finished with exit code 1

```
So I think I made changes correctly. But another question is it related to RAM size or the code could be improved to hang high dimensional matrices?

My RAM size is about 16 GB with pagefile sizing about 176 GB. I am using Windows laptop.

**Comment by rc** [comment]
If you use the 'ls.auto_direct' linear solver, try installing the Mumps solver - it is much more efficient than the default scipy's superLU, or Umfpack.

I have never tried pypardiso, I will check it out.

The error is related to RAM size - direct solvers are notorious for high RAM consumption. You may need to switch to an iterative solver. What kind of equations do you solve?

**Comment by artizzq** [comment]
Hello! Do you mean these?
```
    t1 = Term.new('dw_volume_dot(v, du/dt)',
                  integral, omega, v=v, u=u)
    t2 = Term.new('dw_laplace(m.c, v, u)',
                  integral, omega, m=m, v=v, u=u)
    eq = Equation('balance', t1 + t2)
    eqs = Equations([eq])
```

**Comment by rc** [comment]
Yes, so for the Poisson's equation the CG solver should work well. See [this example](https://sfepy.org/doc-devel/examples/multi_physics-biot_short_syntax.html) on how to setup iterative solvers.

**Comment by artizzq** [comment]
Thanks, its working now.
