### ISSUE TITLE
Arm64 Mac install

### ISSUE THREAD

**Issue by joshu3a** [sfepy/sfepy#983]
Hi there,

I am trying to install safety on an Arm64 Mac, but having no luck. Is this a known issue? Is there any work around? 

Here is what I get is I just try pip install:

```
% pip install sfepy          
Collecting sfepy
  Using cached sfepy-2023.1.tar.gz (14.9 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [24 lines of output]
      Traceback (most recent call last):
        File "/opt/homebrew/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/opt/homebrew/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/opt/homebrew/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/build_meta.py", line 338, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/build_meta.py", line 320, in _get_build_requires
          self.run_setup()
        File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/build_meta.py", line 485, in run_setup
          self).run_setup(setup_script=setup_script)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 215, in <module>
        File "<string>", line 106, in check_versions
        File "/private/var/folders/2_/j_j8jwdd0kv41r_ny80h_lfw0000gn/T/pip-install-8btxbbm1/sfepy_c6a450f80851407fa2e39b75312037cb/./tools/build_helpers.py", line 314, in package_check
          raise RuntimeError(msgs['missing'] % pkg_name)
      RuntimeError: tables is missing
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

Any help would be greatly appreciated!

Josh

**Comment by STOKEDMODELLER** [comment]
Hi Josh,

It seems the installation of sfepy is failing due to a missing dependency, specifically the `tables` package. To resolve this issue, you can try installing the missing package first, and then try installing sfepy again.

First, try installing the `tables` package using pip:

```bash
pip install tables
```

If you face any issue during the installation of tables package, try using the --no-binary option with pip:

```bash
pip install --no-binary=tables tables

```
Once the tables package is installed, you can try installing sfepy again:

```bash
pip install sfepy
```

However, if you still face issues with the installation of sfepy on your Arm64 Mac, it might be helpful to install it from the source. Here are the steps to do that:

1.	Clone the sfepy repository:
```bash
git clone https://github.com/sfepy/sfepy.git 
```
2.	Change to the cloned directory:
```bash
cd sfepy 
```

3.	Install the required dependencies:
```bash
pip install -r requirements.txt 
```


4.	Build and install sfepy:
```bash
python setup.py build python setup.py install 
```

I hope this helps! Let me know if you face any further issues.

**Comment by zlzq-duanzq** [comment]
> Hi Josh,
> 
> It seems the installation of sfepy is failing due to a missing dependency, specifically the `tables` package. To resolve this issue, you can try installing the missing package first, and then try installing sfepy again.
> 
> First, try installing the `tables` package using pip:
> 
> ```shell
> pip install tables
> ```
> 
> If you face any issue during the installation of tables package, try using the --no-binary option with pip:
> 
> ```shell
> pip install --no-binary=tables tables
> ```
> 
> Once the tables package is installed, you can try installing sfepy again:
> 
> ```shell
> pip install sfepy
> ```
> 
> However, if you still face issues with the installation of sfepy on your Arm64 Mac, it might be helpful to install it from the source. Here are the steps to do that:
> 
> 1. Clone the sfepy repository:
> 
> ```shell
> git clone https://github.com/sfepy/sfepy.git 
> ```
> 
> 2. Change to the cloned directory:
> 
> ```shell
> cd sfepy 
> ```
> 
> 3. Install the required dependencies:
> 
> ```shell
> pip install -r requirements.txt 
> ```
> 
> 4. Build and install sfepy:
> 
> ```shell
> python setup.py build python setup.py install 
> ```
> 
> I hope this helps! Let me know if you face any further issues.

No such file: requirements.txt
