### ISSUE TITLE
Error with term dw_jump when  approx order is increased

### ISSUE THREAD

**Issue by peppe988** [sfepy/sfepy#999]
Dear sfepy I get an error when I try to increase the approx order of my fields to values greater than 1. Here is the code:
[Sfepy_issue.zip](https://github.com/sfepy/sfepy/files/11652299/Sfepy_issue.zip)

The error is this, would you happen to have any idea? I am actually confused about why the second field is given as tr(phi_2) in the tutorials on how to use the dw_jump term, so I don't know if that can be the problem:
```

sfepy: left over: ['__name__', '__doc__', '__package__', '__loader__', '__spec__', '__file__', '__cached__', '__builtins__', 'print_function', 'absolute_import', 'data_dir', 'refine_mesh', 'output', 'np', 'Struct', 'fsolve', 'Delta_right', 'Delta_left', 'g', 'approx_order', 'equations', 'verbose', '_filename']
sfepy: reading mesh (/Users/giuseppecolletta/Downloads/sfepy_issue_2 (1)/Sfepy-example.mesh)...
sfepy:   number of vertices: 3959
sfepy:   number of cells:
sfepy:     3_4: 18807
sfepy: ...done in 0.06 s
sfepy: creating regions...
sfepy:     Omega
sfepy:     Omega_bridge
sfepy:     Omega_right
sfepy:     Omega_left
sfepy:     Gamma_Left
sfepy:     Gamma_Right
sfepy:     Gamma_left_bridge_1
sfepy:     Gamma_right_bridge_1
sfepy:     Gamma_left_bridge
sfepy:     Gamma_right_bridge
sfepy:     Gamma_bridge_left
sfepy:     Gamma_bridge_right
sfepy: ...done in 0.06 s
sfepy: equation "Usadel_left":
sfepy:  + dw_laplace.i.Omega_left( s_left, phi_left)
+ dw_jump.i.Gamma_left_bridge(s_left, phi_left, tr(phi_bridge))
= 0
sfepy: equation "Usadel_right":
sfepy:  + dw_laplace.i.Omega_right( s_right, phi_right)
+ dw_jump.i.Gamma_right_bridge(s_right, phi_right, tr(phi_bridge))
= 0
sfepy: equation "Usadel_bridge":
sfepy:  + dw_laplace.i.Omega_bridge( s_bridge, phi_bridge)
+dw_jump.i.Gamma_bridge_right(s_bridge, phi_bridge, tr(phi_right))
+dw_jump.i.Gamma_bridge_left(s_bridge, phi_bridge, tr(phi_left))
= 0
sfepy: using solvers:
                ts: no ts
               nls: newton
                ls: ls
sfepy: updating variables...
sfepy: ...done
sfepy: setting up dof connectivities...
Traceback (most recent call last):
  File "/Users/giuseppecolletta/opt/anaconda3/envs/sfepy2/bin/sfepy-run", line 8, in <module>
    sys.exit(main())
  File "/Users/giuseppecolletta/opt/anaconda3/envs/sfepy2/lib/python3.7/site-packages/sfepy/scripts/simple.py", line 330, in main
    app()
  File "/Users/giuseppecolletta/opt/anaconda3/envs/sfepy2/lib/python3.7/site-packages/sfepy/applications/application.py", line 29, in call_basic
    return self.call(**kwargs)
  File "/Users/giuseppecolletta/opt/anaconda3/envs/sfepy2/lib/python3.7/site-packages/sfepy/applications/pde_solver_app.py", line 232, in call
    post_process_hook_final=self.post_process_hook_final)
  File "/Users/giuseppecolletta/opt/anaconda3/envs/sfepy2/lib/python3.7/site-packages/sfepy/discrete/problem.py", line 1452, in solve
    self.time_update(tss.ts)
  File "/Users/giuseppecolletta/opt/anaconda3/envs/sfepy2/lib/python3.7/site-packages/sfepy/discrete/problem.py", line 692, in time_update
    functions, create_matrix, is_matrix)
  File "/Users/giuseppecolletta/opt/anaconda3/envs/sfepy2/lib/python3.7/site-packages/sfepy/discrete/problem.py", line 641, in update_equations
    verbose=self.conf.get('verbose', True))
  File "/Users/giuseppecolletta/opt/anaconda3/envs/sfepy2/lib/python3.7/site-packages/sfepy/discrete/equations.py", line 313, in time_update
    active_only=active_only)
  File "/Users/giuseppecolletta/opt/anaconda3/envs/sfepy2/lib/python3.7/site-packages/sfepy/discrete/variables.py", line 95, in create_adof_conns
    field.setup_extra_data(info.ps_tg, info)
  File "/Users/giuseppecolletta/opt/anaconda3/envs/sfepy2/lib/python3.7/site-packages/sfepy/discrete/fem/fields_base.py", line 1203, in setup_extra_data
    self.setup_surface_data(reg, mreg_name)
  File "/Users/giuseppecolletta/opt/anaconda3/envs/sfepy2/lib/python3.7/site-packages/sfepy/discrete/fem/fields_base.py", line 1234, in setup_surface_data
    sd.setup_mirror_connectivity(region, trace_region)
  File "/Users/giuseppecolletta/opt/anaconda3/envs/sfepy2/lib/python3.7/site-packages/sfepy/discrete/fem/fe_surface.py", line 97, in setup_mirror_connectivity
    mmap = get_omap(mregion, self.ori_map)
  File "/Users/giuseppecolletta/opt/anaconda3/envs/sfepy2/lib/python3.7/site-packages/sfepy/discrete/fem/fe_surface.py", line 94, in get_omap
    return ori_map[oris[conn.indptr[fis[:, 0]] + fis[:, 1]]]
TypeError: 'NoneType' object is not subscriptable

```

**Comment by rc** [comment]
Yes, unfortunately, the `tr()`is currently broken for order > 1. Pinging @vlukes who might have plans how to fix it.
